//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// The confidential and proprietary information contained in this file may     
// only be used by a person authorised under and to the extent permitted       
// by a subsisting licensing agreement from ARM Limited.                       
//                                                                             
//            (C) COPYRIGHT 2005-2015 ARM Limited.
//                ALL RIGHTS RESERVED                                          
//                                                                             
// This entire notice must be reproduced on all copies of this file            
// and copies of this file may only be made by a person if such person is      
// permitted to do so under the terms of a subsisting license agreement        
// from ARM Limited.                                                           
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Top-Level Verilog file is auto-generated by AMBA Designer ADr3p5-01eac0-build-0005

//                                                                             
// Stitcher: generic_stitcher_core v3.1, built on Dec  1 2015
//                                                                             
// Filename: nic400_peri_bus_r0p00.v
// Created : Thu Jan 12 06:24:49 2017                            
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Generated with Validator version1.0


//-----------------------------------------------------------------------------
// Module Declaration nic400_peri_bus_r0p00
//-----------------------------------------------------------------------------

module nic400_peri_bus_r0p00 (
  
// Instance: u_cd_i_pclk_peri_bus, Port: cpu2peri_s0

  awid_cpu2peri_s0,
  awaddr_cpu2peri_s0,
  awlen_cpu2peri_s0,
  awsize_cpu2peri_s0,
  awburst_cpu2peri_s0,
  awlock_cpu2peri_s0,
  awcache_cpu2peri_s0,
  awprot_cpu2peri_s0,
  awvalid_cpu2peri_s0,
  awready_cpu2peri_s0,
  wdata_cpu2peri_s0,
  wstrb_cpu2peri_s0,
  wlast_cpu2peri_s0,
  wvalid_cpu2peri_s0,
  wready_cpu2peri_s0,
  bid_cpu2peri_s0,
  bresp_cpu2peri_s0,
  bvalid_cpu2peri_s0,
  bready_cpu2peri_s0,
  arid_cpu2peri_s0,
  araddr_cpu2peri_s0,
  arlen_cpu2peri_s0,
  arsize_cpu2peri_s0,
  arburst_cpu2peri_s0,
  arlock_cpu2peri_s0,
  arcache_cpu2peri_s0,
  arprot_cpu2peri_s0,
  arvalid_cpu2peri_s0,
  arready_cpu2peri_s0,
  rid_cpu2peri_s0,
  rdata_cpu2peri_s0,
  rresp_cpu2peri_s0,
  rlast_cpu2peri_s0,
  rvalid_cpu2peri_s0,
  rready_cpu2peri_s0,
  
// Instance: u_cd_i_pclk_peri_bus, Port: ddr_m4

  paddr_ddr_m4,
  pselx_ddr_m4,
  penable_ddr_m4,
  pwrite_ddr_m4,
  prdata_ddr_m4,
  pwdata_ddr_m4,
  pready_ddr_m4,
  pslverr_ddr_m4,
  
// Instance: u_cd_i_pclk_peri_bus, Port: peri0_m0

  paddr_peri0_m0,
  pselx_peri0_m0,
  penable_peri0_m0,
  pwrite_peri0_m0,
  prdata_peri0_m0,
  pwdata_peri0_m0,
  
// Instance: u_cd_i_pclk_peri_bus, Port: peri1_m1

  paddr_peri1_m1,
  pselx_peri1_m1,
  penable_peri1_m1,
  pwrite_peri1_m1,
  prdata_peri1_m1,
  pwdata_peri1_m1,
  
// Instance: u_cd_i_pclk_peri_bus, Port: peri2_m2

  paddr_peri2_m2,
  pselx_peri2_m2,
  penable_peri2_m2,
  pwrite_peri2_m2,
  prdata_peri2_m2,
  pwdata_peri2_m2,
  
// Instance: u_cd_i_pclk_peri_bus, Port: usb3_m3

  haddr_usb3_m3,
  hburst_usb3_m3,
  hprot_usb3_m3,
  hsize_usb3_m3,
  htrans_usb3_m3,
  hwdata_usb3_m3,
  hwrite_usb3_m3,
  hrdata_usb3_m3,
  hreadyout_usb3_m3,
  hresp_usb3_m3,
  hselx_usb3_m3,
  hready_usb3_m3,

//  Non-bus signals

  i_pclk_peri_busclk,
  i_pclk_peri_busclken,
  i_pclk_peri_busresetn,
  mainclk,
  mainclk_r,
  mainresetn,
  mainresetn_r

);



//-----------------------------------------------------------------------------
// Port Declarations
//-----------------------------------------------------------------------------


// Instance: u_cd_i_pclk_peri_bus, Port: cpu2peri_s0

input  [4:0]  awid_cpu2peri_s0;
input  [31:0] awaddr_cpu2peri_s0;
input  [7:0]  awlen_cpu2peri_s0;
input  [2:0]  awsize_cpu2peri_s0;
input  [1:0]  awburst_cpu2peri_s0;
input         awlock_cpu2peri_s0;
input  [3:0]  awcache_cpu2peri_s0;
input  [2:0]  awprot_cpu2peri_s0;
input         awvalid_cpu2peri_s0;
output        awready_cpu2peri_s0;
input  [31:0] wdata_cpu2peri_s0;
input  [3:0]  wstrb_cpu2peri_s0;
input         wlast_cpu2peri_s0;
input         wvalid_cpu2peri_s0;
output        wready_cpu2peri_s0;
output [4:0]  bid_cpu2peri_s0;
output [1:0]  bresp_cpu2peri_s0;
output        bvalid_cpu2peri_s0;
input         bready_cpu2peri_s0;
input  [4:0]  arid_cpu2peri_s0;
input  [31:0] araddr_cpu2peri_s0;
input  [7:0]  arlen_cpu2peri_s0;
input  [2:0]  arsize_cpu2peri_s0;
input  [1:0]  arburst_cpu2peri_s0;
input         arlock_cpu2peri_s0;
input  [3:0]  arcache_cpu2peri_s0;
input  [2:0]  arprot_cpu2peri_s0;
input         arvalid_cpu2peri_s0;
output        arready_cpu2peri_s0;
output [4:0]  rid_cpu2peri_s0;
output [31:0] rdata_cpu2peri_s0;
output [1:0]  rresp_cpu2peri_s0;
output        rlast_cpu2peri_s0;
output        rvalid_cpu2peri_s0;
input         rready_cpu2peri_s0;

// Instance: u_cd_i_pclk_peri_bus, Port: ddr_m4

output [31:0] paddr_ddr_m4;
output        pselx_ddr_m4;
output        penable_ddr_m4;
output        pwrite_ddr_m4;
input  [31:0] prdata_ddr_m4;
output [31:0] pwdata_ddr_m4;
input         pready_ddr_m4;
input         pslverr_ddr_m4;

// Instance: u_cd_i_pclk_peri_bus, Port: peri0_m0

output [31:0] paddr_peri0_m0;
output        pselx_peri0_m0;
output        penable_peri0_m0;
output        pwrite_peri0_m0;
input  [31:0] prdata_peri0_m0;
output [31:0] pwdata_peri0_m0;

// Instance: u_cd_i_pclk_peri_bus, Port: peri1_m1

output [31:0] paddr_peri1_m1;
output        pselx_peri1_m1;
output        penable_peri1_m1;
output        pwrite_peri1_m1;
input  [31:0] prdata_peri1_m1;
output [31:0] pwdata_peri1_m1;

// Instance: u_cd_i_pclk_peri_bus, Port: peri2_m2

output [31:0] paddr_peri2_m2;
output        pselx_peri2_m2;
output        penable_peri2_m2;
output        pwrite_peri2_m2;
input  [31:0] prdata_peri2_m2;
output [31:0] pwdata_peri2_m2;

// Instance: u_cd_i_pclk_peri_bus, Port: usb3_m3

output [31:0] haddr_usb3_m3;
output [2:0]  hburst_usb3_m3;
output [3:0]  hprot_usb3_m3;
output [2:0]  hsize_usb3_m3;
output [1:0]  htrans_usb3_m3;
output [31:0] hwdata_usb3_m3;
output        hwrite_usb3_m3;
input  [31:0] hrdata_usb3_m3;
input         hreadyout_usb3_m3;
input         hresp_usb3_m3;
output        hselx_usb3_m3;
output        hready_usb3_m3;

//  Non-bus signals

input         i_pclk_peri_busclk;
input         i_pclk_peri_busclken;
input         i_pclk_peri_busresetn;
input         mainclk;
input         mainclk_r;
input         mainresetn;
input         mainresetn_r;



//-----------------------------------------------------------------------------
// Internal Wire Declarations
//-----------------------------------------------------------------------------

wire           arready_cpu2peri_s0;
wire           awready_cpu2peri_s0;
wire   [4:0]   bid_cpu2peri_s0;
wire   [1:0]   bresp_cpu2peri_s0;
wire           bvalid_cpu2peri_s0;
wire   [31:0]  haddr_usb3_m3;
wire   [2:0]   hburst_usb3_m3;
wire   [3:0]   hprot_usb3_m3;
wire           hready_usb3_m3;
wire           hselx_usb3_m3;
wire   [2:0]   hsize_usb3_m3;
wire   [1:0]   htrans_usb3_m3;
wire   [31:0]  hwdata_usb3_m3;
wire           hwrite_usb3_m3;
wire   [31:0]  paddr_ddr_m4;
wire   [31:0]  paddr_peri0_m0;
wire   [31:0]  paddr_peri1_m1;
wire   [31:0]  paddr_peri2_m2;
wire           penable_ddr_m4;
wire           penable_peri0_m0;
wire           penable_peri1_m1;
wire           penable_peri2_m2;
wire           pselx_ddr_m4;
wire           pselx_peri0_m0;
wire           pselx_peri1_m1;
wire           pselx_peri2_m2;
wire   [31:0]  pwdata_ddr_m4;
wire   [31:0]  pwdata_peri0_m0;
wire   [31:0]  pwdata_peri1_m1;
wire   [31:0]  pwdata_peri2_m2;
wire           pwrite_ddr_m4;
wire           pwrite_peri0_m0;
wire           pwrite_peri1_m1;
wire           pwrite_peri2_m2;
wire   [31:0]  rdata_cpu2peri_s0;
wire   [4:0]   rid_cpu2peri_s0;
wire           rlast_cpu2peri_s0;
wire   [1:0]   rresp_cpu2peri_s0;
wire           rvalid_cpu2peri_s0;
wire           wready_cpu2peri_s0;
wire           a_rpntr_bin_slave_0_ib_int;    //slave_0_ib_int - u_cd_i_pclk_peri_bus
wire           a_rpntr_bin_slave_1_ib_int;    //slave_1_ib_int - u_cd_i_pclk_peri_bus
wire           a_rpntr_bin_slave_2_ib_int;    //slave_2_ib_int - u_cd_i_pclk_peri_bus
wire           a_rpntr_bin_slave_3_ib_int;    //slave_3_ib_int - u_cd_i_pclk_peri_bus
wire           a_rpntr_bin_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   a_rpntr_gry_slave_0_ib_int;    //slave_0_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   a_rpntr_gry_slave_1_ib_int;    //slave_1_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   a_rpntr_gry_slave_2_ib_int;    //slave_2_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   a_rpntr_gry_slave_3_ib_int;    //slave_3_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   a_rpntr_gry_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_i_pclk_peri_bus
wire   [64:0]  ar_data_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   ar_wpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [64:0]  aw_data_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   aw_wpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire           b_rpntr_bin_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   b_rpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [40:0]  d_data_slave_0_ib_int;    //slave_0_ib_int - u_cd_i_pclk_peri_bus
wire   [40:0]  d_data_slave_1_ib_int;    //slave_1_ib_int - u_cd_i_pclk_peri_bus
wire   [40:0]  d_data_slave_2_ib_int;    //slave_2_ib_int - u_cd_i_pclk_peri_bus
wire   [40:0]  d_data_slave_3_ib_int;    //slave_3_ib_int - u_cd_i_pclk_peri_bus
wire   [40:0]  d_data_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   d_wpntr_gry_slave_0_ib_int;    //slave_0_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   d_wpntr_gry_slave_1_ib_int;    //slave_1_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   d_wpntr_gry_slave_2_ib_int;    //slave_2_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   d_wpntr_gry_slave_3_ib_int;    //slave_3_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   d_wpntr_gry_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_i_pclk_peri_bus
wire           pack_cpu2peri_s0_ib_apb_int;    //cpu2peri_s0_ib_apb_int - u_cd_i_pclk_peri_bus
wire           pack_slave_0_ib_apb_int;    //slave_0_ib_apb_int - u_cd_i_pclk_peri_bus
wire           pack_slave_1_ib_apb_int;    //slave_1_ib_apb_int - u_cd_i_pclk_peri_bus
wire           pack_slave_2_ib_apb_int;    //slave_2_ib_apb_int - u_cd_i_pclk_peri_bus
wire           pack_slave_3_ib_apb_int;    //slave_3_ib_apb_int - u_cd_i_pclk_peri_bus
wire           pack_usb3_m3_ib_apb_int;    //usb3_m3_ib_apb_int - u_cd_i_pclk_peri_bus
wire   [32:0]  prevpayld_cpu2peri_s0_ib_apb_int;    //cpu2peri_s0_ib_apb_int - u_cd_i_pclk_peri_bus
wire   [32:0]  prevpayld_slave_0_ib_apb_int;    //slave_0_ib_apb_int - u_cd_i_pclk_peri_bus
wire   [32:0]  prevpayld_slave_1_ib_apb_int;    //slave_1_ib_apb_int - u_cd_i_pclk_peri_bus
wire   [32:0]  prevpayld_slave_2_ib_apb_int;    //slave_2_ib_apb_int - u_cd_i_pclk_peri_bus
wire   [32:0]  prevpayld_slave_3_ib_apb_int;    //slave_3_ib_apb_int - u_cd_i_pclk_peri_bus
wire   [32:0]  prevpayld_usb3_m3_ib_apb_int;    //usb3_m3_ib_apb_int - u_cd_i_pclk_peri_bus
wire           r_rpntr_bin_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   r_rpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [36:0]  w_data_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire           w_rpntr_bin_slave_0_ib_int;    //slave_0_ib_int - u_cd_i_pclk_peri_bus
wire           w_rpntr_bin_slave_1_ib_int;    //slave_1_ib_int - u_cd_i_pclk_peri_bus
wire           w_rpntr_bin_slave_2_ib_int;    //slave_2_ib_int - u_cd_i_pclk_peri_bus
wire           w_rpntr_bin_slave_3_ib_int;    //slave_3_ib_int - u_cd_i_pclk_peri_bus
wire           w_rpntr_bin_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   w_rpntr_gry_slave_0_ib_int;    //slave_0_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   w_rpntr_gry_slave_1_ib_int;    //slave_1_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   w_rpntr_gry_slave_2_ib_int;    //slave_2_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   w_rpntr_gry_slave_3_ib_int;    //slave_3_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   w_rpntr_gry_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_i_pclk_peri_bus
wire   [1:0]   w_wpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_i_pclk_peri_bus
wire   [58:0]  a_data_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_cd_main
wire   [58:0]  a_data_slave_0_ib_int;    //slave_0_ib_int - u_cd_main
wire   [58:0]  a_data_slave_1_ib_int;    //slave_1_ib_int - u_cd_main
wire   [58:0]  a_data_slave_2_ib_int;    //slave_2_ib_int - u_cd_main
wire   [58:0]  a_data_slave_3_ib_int;    //slave_3_ib_int - u_cd_main
wire   [58:0]  a_data_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_main
wire           a_valid_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_cd_main
wire   [1:0]   a_wpntr_gry_slave_0_ib_int;    //slave_0_ib_int - u_cd_main
wire   [1:0]   a_wpntr_gry_slave_1_ib_int;    //slave_1_ib_int - u_cd_main
wire   [1:0]   a_wpntr_gry_slave_2_ib_int;    //slave_2_ib_int - u_cd_main
wire   [1:0]   a_wpntr_gry_slave_3_ib_int;    //slave_3_ib_int - u_cd_main
wire   [1:0]   a_wpntr_gry_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_main
wire           ar_rpntr_bin_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire   [1:0]   ar_rpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire           aw_rpntr_bin_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire   [1:0]   aw_rpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire   [6:0]   b_data_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire   [1:0]   b_wpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire           d_ready_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_cd_main
wire           d_rpntr_bin_slave_0_ib_int;    //slave_0_ib_int - u_cd_main
wire           d_rpntr_bin_slave_1_ib_int;    //slave_1_ib_int - u_cd_main
wire           d_rpntr_bin_slave_2_ib_int;    //slave_2_ib_int - u_cd_main
wire           d_rpntr_bin_slave_3_ib_int;    //slave_3_ib_int - u_cd_main
wire           d_rpntr_bin_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_main
wire   [1:0]   d_rpntr_gry_slave_0_ib_int;    //slave_0_ib_int - u_cd_main
wire   [1:0]   d_rpntr_gry_slave_1_ib_int;    //slave_1_ib_int - u_cd_main
wire   [1:0]   d_rpntr_gry_slave_2_ib_int;    //slave_2_ib_int - u_cd_main
wire   [1:0]   d_rpntr_gry_slave_3_ib_int;    //slave_3_ib_int - u_cd_main
wire   [1:0]   d_rpntr_gry_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_main
wire   [71:0]  pfwdpayld_cpu2peri_s0_ib_apb_int;    //cpu2peri_s0_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_slave_0_ib_apb_int;    //slave_0_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_slave_1_ib_apb_int;    //slave_1_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_slave_2_ib_apb_int;    //slave_2_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_slave_3_ib_apb_int;    //slave_3_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_usb3_m3_ib_apb_int;    //usb3_m3_ib_apb_int - u_cd_main
wire   [31:0]  prdata_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_cd_main
wire   [31:0]  prdata_slave_0_ib_apb;    //slave_0_ib_apb - u_cd_main
wire   [31:0]  prdata_slave_1_ib_apb;    //slave_1_ib_apb - u_cd_main
wire   [31:0]  prdata_slave_2_ib_apb;    //slave_2_ib_apb - u_cd_main
wire   [31:0]  prdata_slave_3_ib_apb;    //slave_3_ib_apb - u_cd_main
wire   [31:0]  prdata_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_cd_main
wire           pready_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_cd_main
wire           pready_slave_0_ib_apb;    //slave_0_ib_apb - u_cd_main
wire           pready_slave_1_ib_apb;    //slave_1_ib_apb - u_cd_main
wire           pready_slave_2_ib_apb;    //slave_2_ib_apb - u_cd_main
wire           pready_slave_3_ib_apb;    //slave_3_ib_apb - u_cd_main
wire           pready_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_cd_main
wire           preq_cpu2peri_s0_ib_apb_int;    //cpu2peri_s0_ib_apb_int - u_cd_main
wire           preq_slave_0_ib_apb_int;    //slave_0_ib_apb_int - u_cd_main
wire           preq_slave_1_ib_apb_int;    //slave_1_ib_apb_int - u_cd_main
wire           preq_slave_2_ib_apb_int;    //slave_2_ib_apb_int - u_cd_main
wire           preq_slave_3_ib_apb_int;    //slave_3_ib_apb_int - u_cd_main
wire           preq_usb3_m3_ib_apb_int;    //usb3_m3_ib_apb_int - u_cd_main
wire           pslverr_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_cd_main
wire           pslverr_slave_0_ib_apb;    //slave_0_ib_apb - u_cd_main
wire           pslverr_slave_1_ib_apb;    //slave_1_ib_apb - u_cd_main
wire           pslverr_slave_2_ib_apb;    //slave_2_ib_apb - u_cd_main
wire           pslverr_slave_3_ib_apb;    //slave_3_ib_apb - u_cd_main
wire           pslverr_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_cd_main
wire   [39:0]  r_data_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire   [1:0]   r_wpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire   [36:0]  w_data_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_cd_main
wire   [36:0]  w_data_slave_0_ib_int;    //slave_0_ib_int - u_cd_main
wire   [36:0]  w_data_slave_1_ib_int;    //slave_1_ib_int - u_cd_main
wire   [36:0]  w_data_slave_2_ib_int;    //slave_2_ib_int - u_cd_main
wire   [36:0]  w_data_slave_3_ib_int;    //slave_3_ib_int - u_cd_main
wire   [36:0]  w_data_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_main
wire           w_rpntr_bin_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire   [1:0]   w_rpntr_gry_cpu2peri_s0_ib_int;    //cpu2peri_s0_ib_int - u_cd_main
wire           w_valid_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_cd_main
wire   [1:0]   w_wpntr_gry_slave_0_ib_int;    //slave_0_ib_int - u_cd_main
wire   [1:0]   w_wpntr_gry_slave_1_ib_int;    //slave_1_ib_int - u_cd_main
wire   [1:0]   w_wpntr_gry_slave_2_ib_int;    //slave_2_ib_int - u_cd_main
wire   [1:0]   w_wpntr_gry_slave_3_ib_int;    //slave_3_ib_int - u_cd_main
wire   [1:0]   w_wpntr_gry_usb3_m3_ib_int;    //usb3_m3_ib_int - u_cd_main
wire           a_ready_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_r_cd_main
wire   [40:0]  d_data_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_r_cd_main
wire           d_valid_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_r_cd_main
wire   [31:0]  paddr_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_r_cd_main
wire   [31:0]  paddr_slave_0_ib_apb;    //slave_0_ib_apb - u_r_cd_main
wire   [31:0]  paddr_slave_1_ib_apb;    //slave_1_ib_apb - u_r_cd_main
wire   [31:0]  paddr_slave_2_ib_apb;    //slave_2_ib_apb - u_r_cd_main
wire   [31:0]  paddr_slave_3_ib_apb;    //slave_3_ib_apb - u_r_cd_main
wire   [31:0]  paddr_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_r_cd_main
wire           penable_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_r_cd_main
wire           penable_slave_0_ib_apb;    //slave_0_ib_apb - u_r_cd_main
wire           penable_slave_1_ib_apb;    //slave_1_ib_apb - u_r_cd_main
wire           penable_slave_2_ib_apb;    //slave_2_ib_apb - u_r_cd_main
wire           penable_slave_3_ib_apb;    //slave_3_ib_apb - u_r_cd_main
wire           penable_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_r_cd_main
wire           pselx_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_r_cd_main
wire           pselx_slave_0_ib_apb;    //slave_0_ib_apb - u_r_cd_main
wire           pselx_slave_1_ib_apb;    //slave_1_ib_apb - u_r_cd_main
wire           pselx_slave_2_ib_apb;    //slave_2_ib_apb - u_r_cd_main
wire           pselx_slave_3_ib_apb;    //slave_3_ib_apb - u_r_cd_main
wire           pselx_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_slave_0_ib_apb;    //slave_0_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_slave_1_ib_apb;    //slave_1_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_slave_2_ib_apb;    //slave_2_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_slave_3_ib_apb;    //slave_3_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_r_cd_main
wire           pwrite_cpu2peri_s0_ib_apb;    //cpu2peri_s0_ib_apb - u_r_cd_main
wire           pwrite_slave_0_ib_apb;    //slave_0_ib_apb - u_r_cd_main
wire           pwrite_slave_1_ib_apb;    //slave_1_ib_apb - u_r_cd_main
wire           pwrite_slave_2_ib_apb;    //slave_2_ib_apb - u_r_cd_main
wire           pwrite_slave_3_ib_apb;    //slave_3_ib_apb - u_r_cd_main
wire           pwrite_usb3_m3_ib_apb;    //usb3_m3_ib_apb - u_r_cd_main
wire   [1:0]   rsb_bin_rptr_main_ml_s;    //main_ml_s - u_r_cd_main
wire   [1:0]   rsb_bin_rptr_main_sl_s;    //main_sl_s - u_r_cd_main
wire   [7:0]   rsb_data_main_ml_m;    //main_ml_m - u_r_cd_main
wire   [7:0]   rsb_data_main_sl_m;    //main_sl_m - u_r_cd_main
wire   [2:0]   rsb_rptr_main_ml_s;    //main_ml_s - u_r_cd_main
wire   [2:0]   rsb_rptr_main_sl_s;    //main_sl_s - u_r_cd_main
wire   [2:0]   rsb_wptr_main_ml_m;    //main_ml_m - u_r_cd_main
wire   [2:0]   rsb_wptr_main_sl_m;    //main_sl_m - u_r_cd_main
wire           w_ready_peri_gpv_ib1_int;    //peri_gpv_ib1_int - u_r_cd_main
wire   [1:0]   rsb_bin_rptr_main_ml_m;    //main_master_s - u_rsb_conns
wire   [1:0]   rsb_bin_rptr_main_sl_m;    //main_slave_s - u_rsb_conns
wire   [7:0]   rsb_data_main_ml_s;    //main_master_m - u_rsb_conns
wire   [7:0]   rsb_data_main_sl_s;    //main_slave_m - u_rsb_conns
wire   [2:0]   rsb_rptr_main_ml_m;    //main_master_s - u_rsb_conns
wire   [2:0]   rsb_rptr_main_sl_m;    //main_slave_s - u_rsb_conns
wire   [2:0]   rsb_wptr_main_ml_s;    //main_master_m - u_rsb_conns
wire   [2:0]   rsb_wptr_main_sl_s;    //main_slave_m - u_rsb_conns
wire   [31:0]  araddr_cpu2peri_s0;
wire   [1:0]   arburst_cpu2peri_s0;
wire   [3:0]   arcache_cpu2peri_s0;
wire   [4:0]   arid_cpu2peri_s0;
wire   [7:0]   arlen_cpu2peri_s0;
wire           arlock_cpu2peri_s0;
wire   [2:0]   arprot_cpu2peri_s0;
wire   [2:0]   arsize_cpu2peri_s0;
wire           arvalid_cpu2peri_s0;
wire   [31:0]  awaddr_cpu2peri_s0;
wire   [1:0]   awburst_cpu2peri_s0;
wire   [3:0]   awcache_cpu2peri_s0;
wire   [4:0]   awid_cpu2peri_s0;
wire   [7:0]   awlen_cpu2peri_s0;
wire           awlock_cpu2peri_s0;
wire   [2:0]   awprot_cpu2peri_s0;
wire   [2:0]   awsize_cpu2peri_s0;
wire           awvalid_cpu2peri_s0;
wire           bready_cpu2peri_s0;
wire   [31:0]  hrdata_usb3_m3;
wire           hreadyout_usb3_m3;
wire           hresp_usb3_m3;
wire           i_pclk_peri_busclk;
wire           i_pclk_peri_busclken;
wire           i_pclk_peri_busresetn;
wire           mainclk;
wire           mainclk_r;
wire           mainresetn;
wire           mainresetn_r;
wire   [31:0]  prdata_ddr_m4;
wire   [31:0]  prdata_peri0_m0;
wire   [31:0]  prdata_peri1_m1;
wire   [31:0]  prdata_peri2_m2;
wire           pready_ddr_m4;
wire           pslverr_ddr_m4;
wire           rready_cpu2peri_s0;
wire   [31:0]  wdata_cpu2peri_s0;
wire           wlast_cpu2peri_s0;
wire   [3:0]   wstrb_cpu2peri_s0;
wire           wvalid_cpu2peri_s0;



//-----------------------------------------------------------------------------
// Sub-Modules Instantiation
//-----------------------------------------------------------------------------

nic400_cd_i_pclk_peri_bus_peri_bus_r0p00     u_cd_i_pclk_peri_bus (
  .awid_cpu2peri_s0     (awid_cpu2peri_s0),    // cpu2peri_s0
  .awaddr_cpu2peri_s0   (awaddr_cpu2peri_s0),    // cpu2peri_s0
  .awlen_cpu2peri_s0    (awlen_cpu2peri_s0),    // cpu2peri_s0
  .awsize_cpu2peri_s0   (awsize_cpu2peri_s0),    // cpu2peri_s0
  .awburst_cpu2peri_s0  (awburst_cpu2peri_s0),    // cpu2peri_s0
  .awlock_cpu2peri_s0   (awlock_cpu2peri_s0),    // cpu2peri_s0
  .awcache_cpu2peri_s0  (awcache_cpu2peri_s0),    // cpu2peri_s0
  .awprot_cpu2peri_s0   (awprot_cpu2peri_s0),    // cpu2peri_s0
  .awvalid_cpu2peri_s0  (awvalid_cpu2peri_s0),    // cpu2peri_s0
  .awready_cpu2peri_s0  (awready_cpu2peri_s0),    // cpu2peri_s0
  .wdata_cpu2peri_s0    (wdata_cpu2peri_s0),    // cpu2peri_s0
  .wstrb_cpu2peri_s0    (wstrb_cpu2peri_s0),    // cpu2peri_s0
  .wlast_cpu2peri_s0    (wlast_cpu2peri_s0),    // cpu2peri_s0
  .wvalid_cpu2peri_s0   (wvalid_cpu2peri_s0),    // cpu2peri_s0
  .wready_cpu2peri_s0   (wready_cpu2peri_s0),    // cpu2peri_s0
  .bid_cpu2peri_s0      (bid_cpu2peri_s0),    // cpu2peri_s0
  .bresp_cpu2peri_s0    (bresp_cpu2peri_s0),    // cpu2peri_s0
  .bvalid_cpu2peri_s0   (bvalid_cpu2peri_s0),    // cpu2peri_s0
  .bready_cpu2peri_s0   (bready_cpu2peri_s0),    // cpu2peri_s0
  .arid_cpu2peri_s0     (arid_cpu2peri_s0),    // cpu2peri_s0
  .araddr_cpu2peri_s0   (araddr_cpu2peri_s0),    // cpu2peri_s0
  .arlen_cpu2peri_s0    (arlen_cpu2peri_s0),    // cpu2peri_s0
  .arsize_cpu2peri_s0   (arsize_cpu2peri_s0),    // cpu2peri_s0
  .arburst_cpu2peri_s0  (arburst_cpu2peri_s0),    // cpu2peri_s0
  .arlock_cpu2peri_s0   (arlock_cpu2peri_s0),    // cpu2peri_s0
  .arcache_cpu2peri_s0  (arcache_cpu2peri_s0),    // cpu2peri_s0
  .arprot_cpu2peri_s0   (arprot_cpu2peri_s0),    // cpu2peri_s0
  .arvalid_cpu2peri_s0  (arvalid_cpu2peri_s0),    // cpu2peri_s0
  .arready_cpu2peri_s0  (arready_cpu2peri_s0),    // cpu2peri_s0
  .rid_cpu2peri_s0      (rid_cpu2peri_s0),    // cpu2peri_s0
  .rdata_cpu2peri_s0    (rdata_cpu2peri_s0),    // cpu2peri_s0
  .rresp_cpu2peri_s0    (rresp_cpu2peri_s0),    // cpu2peri_s0
  .rlast_cpu2peri_s0    (rlast_cpu2peri_s0),    // cpu2peri_s0
  .rvalid_cpu2peri_s0   (rvalid_cpu2peri_s0),    // cpu2peri_s0
  .rready_cpu2peri_s0   (rready_cpu2peri_s0),    // cpu2peri_s0
  .pack_cpu2peri_s0_ib_apb_int (pack_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .preq_cpu2peri_s0_ib_apb_int (preq_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .pfwdpayld_cpu2peri_s0_ib_apb_int (pfwdpayld_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .prevpayld_cpu2peri_s0_ib_apb_int (prevpayld_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .aw_data_cpu2peri_s0_ib_int (aw_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .aw_wpntr_gry_cpu2peri_s0_ib_int (aw_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .aw_rpntr_bin_cpu2peri_s0_ib_int (aw_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .aw_rpntr_gry_cpu2peri_s0_ib_int (aw_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_data_cpu2peri_s0_ib_int (ar_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_wpntr_gry_cpu2peri_s0_ib_int (ar_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_rpntr_bin_cpu2peri_s0_ib_int (ar_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_rpntr_gry_cpu2peri_s0_ib_int (ar_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_data_cpu2peri_s0_ib_int (w_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_wpntr_gry_cpu2peri_s0_ib_int (w_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_rpntr_bin_cpu2peri_s0_ib_int (w_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_rpntr_gry_cpu2peri_s0_ib_int (w_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_data_cpu2peri_s0_ib_int (r_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_wpntr_gry_cpu2peri_s0_ib_int (r_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_rpntr_bin_cpu2peri_s0_ib_int (r_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_rpntr_gry_cpu2peri_s0_ib_int (r_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_data_cpu2peri_s0_ib_int (b_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_wpntr_gry_cpu2peri_s0_ib_int (b_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_rpntr_bin_cpu2peri_s0_ib_int (b_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_rpntr_gry_cpu2peri_s0_ib_int (b_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .paddr_ddr_m4         (paddr_ddr_m4),    // ddr_m4
  .pselx_ddr_m4         (pselx_ddr_m4),    // ddr_m4
  .penable_ddr_m4       (penable_ddr_m4),    // ddr_m4
  .pwrite_ddr_m4        (pwrite_ddr_m4),    // ddr_m4
  .prdata_ddr_m4        (prdata_ddr_m4),    // ddr_m4
  .pwdata_ddr_m4        (pwdata_ddr_m4),    // ddr_m4
  .pready_ddr_m4        (pready_ddr_m4),    // ddr_m4
  .pslverr_ddr_m4       (pslverr_ddr_m4),    // ddr_m4
  .paddr_peri0_m0       (paddr_peri0_m0),    // peri0_m0
  .pselx_peri0_m0       (pselx_peri0_m0),    // peri0_m0
  .penable_peri0_m0     (penable_peri0_m0),    // peri0_m0
  .pwrite_peri0_m0      (pwrite_peri0_m0),    // peri0_m0
  .prdata_peri0_m0      (prdata_peri0_m0),    // peri0_m0
  .pwdata_peri0_m0      (pwdata_peri0_m0),    // peri0_m0
  .paddr_peri1_m1       (paddr_peri1_m1),    // peri1_m1
  .pselx_peri1_m1       (pselx_peri1_m1),    // peri1_m1
  .penable_peri1_m1     (penable_peri1_m1),    // peri1_m1
  .pwrite_peri1_m1      (pwrite_peri1_m1),    // peri1_m1
  .prdata_peri1_m1      (prdata_peri1_m1),    // peri1_m1
  .pwdata_peri1_m1      (pwdata_peri1_m1),    // peri1_m1
  .paddr_peri2_m2       (paddr_peri2_m2),    // peri2_m2
  .pselx_peri2_m2       (pselx_peri2_m2),    // peri2_m2
  .penable_peri2_m2     (penable_peri2_m2),    // peri2_m2
  .pwrite_peri2_m2      (pwrite_peri2_m2),    // peri2_m2
  .prdata_peri2_m2      (prdata_peri2_m2),    // peri2_m2
  .pwdata_peri2_m2      (pwdata_peri2_m2),    // peri2_m2
  .i_pclk_peri_busclken (i_pclk_peri_busclken),    // peri2_m2
  .pack_slave_0_ib_apb_int (pack_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .preq_slave_0_ib_apb_int (preq_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .pfwdpayld_slave_0_ib_apb_int (pfwdpayld_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .prevpayld_slave_0_ib_apb_int (prevpayld_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .a_data_slave_0_ib_int (a_data_slave_0_ib_int),    // slave_0_ib_int
  .a_wpntr_gry_slave_0_ib_int (a_wpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .a_rpntr_bin_slave_0_ib_int (a_rpntr_bin_slave_0_ib_int),    // slave_0_ib_int
  .a_rpntr_gry_slave_0_ib_int (a_rpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .w_data_slave_0_ib_int (w_data_slave_0_ib_int),    // slave_0_ib_int
  .w_wpntr_gry_slave_0_ib_int (w_wpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .w_rpntr_bin_slave_0_ib_int (w_rpntr_bin_slave_0_ib_int),    // slave_0_ib_int
  .w_rpntr_gry_slave_0_ib_int (w_rpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .d_data_slave_0_ib_int (d_data_slave_0_ib_int),    // slave_0_ib_int
  .d_wpntr_gry_slave_0_ib_int (d_wpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .d_rpntr_bin_slave_0_ib_int (d_rpntr_bin_slave_0_ib_int),    // slave_0_ib_int
  .d_rpntr_gry_slave_0_ib_int (d_rpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .pack_slave_1_ib_apb_int (pack_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .preq_slave_1_ib_apb_int (preq_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .pfwdpayld_slave_1_ib_apb_int (pfwdpayld_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .prevpayld_slave_1_ib_apb_int (prevpayld_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .a_data_slave_1_ib_int (a_data_slave_1_ib_int),    // slave_1_ib_int
  .a_wpntr_gry_slave_1_ib_int (a_wpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .a_rpntr_bin_slave_1_ib_int (a_rpntr_bin_slave_1_ib_int),    // slave_1_ib_int
  .a_rpntr_gry_slave_1_ib_int (a_rpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .w_data_slave_1_ib_int (w_data_slave_1_ib_int),    // slave_1_ib_int
  .w_wpntr_gry_slave_1_ib_int (w_wpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .w_rpntr_bin_slave_1_ib_int (w_rpntr_bin_slave_1_ib_int),    // slave_1_ib_int
  .w_rpntr_gry_slave_1_ib_int (w_rpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .d_data_slave_1_ib_int (d_data_slave_1_ib_int),    // slave_1_ib_int
  .d_wpntr_gry_slave_1_ib_int (d_wpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .d_rpntr_bin_slave_1_ib_int (d_rpntr_bin_slave_1_ib_int),    // slave_1_ib_int
  .d_rpntr_gry_slave_1_ib_int (d_rpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .pack_slave_2_ib_apb_int (pack_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .preq_slave_2_ib_apb_int (preq_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .pfwdpayld_slave_2_ib_apb_int (pfwdpayld_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .prevpayld_slave_2_ib_apb_int (prevpayld_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .a_data_slave_2_ib_int (a_data_slave_2_ib_int),    // slave_2_ib_int
  .a_wpntr_gry_slave_2_ib_int (a_wpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .a_rpntr_bin_slave_2_ib_int (a_rpntr_bin_slave_2_ib_int),    // slave_2_ib_int
  .a_rpntr_gry_slave_2_ib_int (a_rpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .w_data_slave_2_ib_int (w_data_slave_2_ib_int),    // slave_2_ib_int
  .w_wpntr_gry_slave_2_ib_int (w_wpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .w_rpntr_bin_slave_2_ib_int (w_rpntr_bin_slave_2_ib_int),    // slave_2_ib_int
  .w_rpntr_gry_slave_2_ib_int (w_rpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .d_data_slave_2_ib_int (d_data_slave_2_ib_int),    // slave_2_ib_int
  .d_wpntr_gry_slave_2_ib_int (d_wpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .d_rpntr_bin_slave_2_ib_int (d_rpntr_bin_slave_2_ib_int),    // slave_2_ib_int
  .d_rpntr_gry_slave_2_ib_int (d_rpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .pack_slave_3_ib_apb_int (pack_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .preq_slave_3_ib_apb_int (preq_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .pfwdpayld_slave_3_ib_apb_int (pfwdpayld_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .prevpayld_slave_3_ib_apb_int (prevpayld_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .a_data_slave_3_ib_int (a_data_slave_3_ib_int),    // slave_3_ib_int
  .a_wpntr_gry_slave_3_ib_int (a_wpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .a_rpntr_bin_slave_3_ib_int (a_rpntr_bin_slave_3_ib_int),    // slave_3_ib_int
  .a_rpntr_gry_slave_3_ib_int (a_rpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .w_data_slave_3_ib_int (w_data_slave_3_ib_int),    // slave_3_ib_int
  .w_wpntr_gry_slave_3_ib_int (w_wpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .w_rpntr_bin_slave_3_ib_int (w_rpntr_bin_slave_3_ib_int),    // slave_3_ib_int
  .w_rpntr_gry_slave_3_ib_int (w_rpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .d_data_slave_3_ib_int (d_data_slave_3_ib_int),    // slave_3_ib_int
  .d_wpntr_gry_slave_3_ib_int (d_wpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .d_rpntr_bin_slave_3_ib_int (d_rpntr_bin_slave_3_ib_int),    // slave_3_ib_int
  .d_rpntr_gry_slave_3_ib_int (d_rpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .i_pclk_peri_busclk   (i_pclk_peri_busclk),    // usb3_m3
  .i_pclk_peri_busresetn (i_pclk_peri_busresetn),    // usb3_m3
  .haddr_usb3_m3        (haddr_usb3_m3),    // usb3_m3
  .hburst_usb3_m3       (hburst_usb3_m3),    // usb3_m3
  .hprot_usb3_m3        (hprot_usb3_m3),    // usb3_m3
  .hsize_usb3_m3        (hsize_usb3_m3),    // usb3_m3
  .htrans_usb3_m3       (htrans_usb3_m3),    // usb3_m3
  .hwdata_usb3_m3       (hwdata_usb3_m3),    // usb3_m3
  .hwrite_usb3_m3       (hwrite_usb3_m3),    // usb3_m3
  .hrdata_usb3_m3       (hrdata_usb3_m3),    // usb3_m3
  .hreadyout_usb3_m3    (hreadyout_usb3_m3),    // usb3_m3
  .hresp_usb3_m3        (hresp_usb3_m3),    // usb3_m3
  .hselx_usb3_m3        (hselx_usb3_m3),    // usb3_m3
  .hready_usb3_m3       (hready_usb3_m3),    // usb3_m3
  .pack_usb3_m3_ib_apb_int (pack_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .preq_usb3_m3_ib_apb_int (preq_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .pfwdpayld_usb3_m3_ib_apb_int (pfwdpayld_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .prevpayld_usb3_m3_ib_apb_int (prevpayld_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .a_data_usb3_m3_ib_int (a_data_usb3_m3_ib_int),    // usb3_m3_ib_int
  .a_wpntr_gry_usb3_m3_ib_int (a_wpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .a_rpntr_bin_usb3_m3_ib_int (a_rpntr_bin_usb3_m3_ib_int),    // usb3_m3_ib_int
  .a_rpntr_gry_usb3_m3_ib_int (a_rpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_data_usb3_m3_ib_int (w_data_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_wpntr_gry_usb3_m3_ib_int (w_wpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_rpntr_bin_usb3_m3_ib_int (w_rpntr_bin_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_rpntr_gry_usb3_m3_ib_int (w_rpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_data_usb3_m3_ib_int (d_data_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_wpntr_gry_usb3_m3_ib_int (d_wpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_rpntr_bin_usb3_m3_ib_int (d_rpntr_bin_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_rpntr_gry_usb3_m3_ib_int (d_rpntr_gry_usb3_m3_ib_int)    // usb3_m3_ib_int
);


nic400_cd_main_peri_bus_r0p00     u_cd_main (
  .paddr_cpu2peri_s0_ib_apb (paddr_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pselx_cpu2peri_s0_ib_apb (pselx_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .penable_cpu2peri_s0_ib_apb (penable_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pwrite_cpu2peri_s0_ib_apb (pwrite_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .prdata_cpu2peri_s0_ib_apb (prdata_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pwdata_cpu2peri_s0_ib_apb (pwdata_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pready_cpu2peri_s0_ib_apb (pready_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pslverr_cpu2peri_s0_ib_apb (pslverr_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pack_cpu2peri_s0_ib_apb_int (pack_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .preq_cpu2peri_s0_ib_apb_int (preq_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .pfwdpayld_cpu2peri_s0_ib_apb_int (pfwdpayld_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .prevpayld_cpu2peri_s0_ib_apb_int (prevpayld_cpu2peri_s0_ib_apb_int),    // cpu2peri_s0_ib_apb_int
  .aw_data_cpu2peri_s0_ib_int (aw_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .aw_wpntr_gry_cpu2peri_s0_ib_int (aw_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .aw_rpntr_bin_cpu2peri_s0_ib_int (aw_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .aw_rpntr_gry_cpu2peri_s0_ib_int (aw_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_data_cpu2peri_s0_ib_int (ar_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_wpntr_gry_cpu2peri_s0_ib_int (ar_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_rpntr_bin_cpu2peri_s0_ib_int (ar_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .ar_rpntr_gry_cpu2peri_s0_ib_int (ar_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_data_cpu2peri_s0_ib_int (w_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_wpntr_gry_cpu2peri_s0_ib_int (w_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_rpntr_bin_cpu2peri_s0_ib_int (w_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .w_rpntr_gry_cpu2peri_s0_ib_int (w_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_data_cpu2peri_s0_ib_int (r_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_wpntr_gry_cpu2peri_s0_ib_int (r_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_rpntr_bin_cpu2peri_s0_ib_int (r_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .r_rpntr_gry_cpu2peri_s0_ib_int (r_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_data_cpu2peri_s0_ib_int (b_data_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_wpntr_gry_cpu2peri_s0_ib_int (b_wpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_rpntr_bin_cpu2peri_s0_ib_int (b_rpntr_bin_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .b_rpntr_gry_cpu2peri_s0_ib_int (b_rpntr_gry_cpu2peri_s0_ib_int),    // cpu2peri_s0_ib_int
  .a_data_peri_gpv_ib1_int (a_data_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .a_valid_peri_gpv_ib1_int (a_valid_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .a_ready_peri_gpv_ib1_int (a_ready_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .w_data_peri_gpv_ib1_int (w_data_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .w_valid_peri_gpv_ib1_int (w_valid_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .w_ready_peri_gpv_ib1_int (w_ready_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .d_data_peri_gpv_ib1_int (d_data_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .d_valid_peri_gpv_ib1_int (d_valid_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .d_ready_peri_gpv_ib1_int (d_ready_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .paddr_slave_0_ib_apb (paddr_slave_0_ib_apb),    // slave_0_ib_apb
  .pselx_slave_0_ib_apb (pselx_slave_0_ib_apb),    // slave_0_ib_apb
  .penable_slave_0_ib_apb (penable_slave_0_ib_apb),    // slave_0_ib_apb
  .pwrite_slave_0_ib_apb (pwrite_slave_0_ib_apb),    // slave_0_ib_apb
  .prdata_slave_0_ib_apb (prdata_slave_0_ib_apb),    // slave_0_ib_apb
  .pwdata_slave_0_ib_apb (pwdata_slave_0_ib_apb),    // slave_0_ib_apb
  .pready_slave_0_ib_apb (pready_slave_0_ib_apb),    // slave_0_ib_apb
  .pslverr_slave_0_ib_apb (pslverr_slave_0_ib_apb),    // slave_0_ib_apb
  .pack_slave_0_ib_apb_int (pack_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .preq_slave_0_ib_apb_int (preq_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .pfwdpayld_slave_0_ib_apb_int (pfwdpayld_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .prevpayld_slave_0_ib_apb_int (prevpayld_slave_0_ib_apb_int),    // slave_0_ib_apb_int
  .a_data_slave_0_ib_int (a_data_slave_0_ib_int),    // slave_0_ib_int
  .a_wpntr_gry_slave_0_ib_int (a_wpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .a_rpntr_bin_slave_0_ib_int (a_rpntr_bin_slave_0_ib_int),    // slave_0_ib_int
  .a_rpntr_gry_slave_0_ib_int (a_rpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .w_data_slave_0_ib_int (w_data_slave_0_ib_int),    // slave_0_ib_int
  .w_wpntr_gry_slave_0_ib_int (w_wpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .w_rpntr_bin_slave_0_ib_int (w_rpntr_bin_slave_0_ib_int),    // slave_0_ib_int
  .w_rpntr_gry_slave_0_ib_int (w_rpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .d_data_slave_0_ib_int (d_data_slave_0_ib_int),    // slave_0_ib_int
  .d_wpntr_gry_slave_0_ib_int (d_wpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .d_rpntr_bin_slave_0_ib_int (d_rpntr_bin_slave_0_ib_int),    // slave_0_ib_int
  .d_rpntr_gry_slave_0_ib_int (d_rpntr_gry_slave_0_ib_int),    // slave_0_ib_int
  .paddr_slave_1_ib_apb (paddr_slave_1_ib_apb),    // slave_1_ib_apb
  .pselx_slave_1_ib_apb (pselx_slave_1_ib_apb),    // slave_1_ib_apb
  .penable_slave_1_ib_apb (penable_slave_1_ib_apb),    // slave_1_ib_apb
  .pwrite_slave_1_ib_apb (pwrite_slave_1_ib_apb),    // slave_1_ib_apb
  .prdata_slave_1_ib_apb (prdata_slave_1_ib_apb),    // slave_1_ib_apb
  .pwdata_slave_1_ib_apb (pwdata_slave_1_ib_apb),    // slave_1_ib_apb
  .pready_slave_1_ib_apb (pready_slave_1_ib_apb),    // slave_1_ib_apb
  .pslverr_slave_1_ib_apb (pslverr_slave_1_ib_apb),    // slave_1_ib_apb
  .pack_slave_1_ib_apb_int (pack_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .preq_slave_1_ib_apb_int (preq_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .pfwdpayld_slave_1_ib_apb_int (pfwdpayld_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .prevpayld_slave_1_ib_apb_int (prevpayld_slave_1_ib_apb_int),    // slave_1_ib_apb_int
  .a_data_slave_1_ib_int (a_data_slave_1_ib_int),    // slave_1_ib_int
  .a_wpntr_gry_slave_1_ib_int (a_wpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .a_rpntr_bin_slave_1_ib_int (a_rpntr_bin_slave_1_ib_int),    // slave_1_ib_int
  .a_rpntr_gry_slave_1_ib_int (a_rpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .w_data_slave_1_ib_int (w_data_slave_1_ib_int),    // slave_1_ib_int
  .w_wpntr_gry_slave_1_ib_int (w_wpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .w_rpntr_bin_slave_1_ib_int (w_rpntr_bin_slave_1_ib_int),    // slave_1_ib_int
  .w_rpntr_gry_slave_1_ib_int (w_rpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .d_data_slave_1_ib_int (d_data_slave_1_ib_int),    // slave_1_ib_int
  .d_wpntr_gry_slave_1_ib_int (d_wpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .d_rpntr_bin_slave_1_ib_int (d_rpntr_bin_slave_1_ib_int),    // slave_1_ib_int
  .d_rpntr_gry_slave_1_ib_int (d_rpntr_gry_slave_1_ib_int),    // slave_1_ib_int
  .paddr_slave_2_ib_apb (paddr_slave_2_ib_apb),    // slave_2_ib_apb
  .pselx_slave_2_ib_apb (pselx_slave_2_ib_apb),    // slave_2_ib_apb
  .penable_slave_2_ib_apb (penable_slave_2_ib_apb),    // slave_2_ib_apb
  .pwrite_slave_2_ib_apb (pwrite_slave_2_ib_apb),    // slave_2_ib_apb
  .prdata_slave_2_ib_apb (prdata_slave_2_ib_apb),    // slave_2_ib_apb
  .pwdata_slave_2_ib_apb (pwdata_slave_2_ib_apb),    // slave_2_ib_apb
  .pready_slave_2_ib_apb (pready_slave_2_ib_apb),    // slave_2_ib_apb
  .pslverr_slave_2_ib_apb (pslverr_slave_2_ib_apb),    // slave_2_ib_apb
  .pack_slave_2_ib_apb_int (pack_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .preq_slave_2_ib_apb_int (preq_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .pfwdpayld_slave_2_ib_apb_int (pfwdpayld_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .prevpayld_slave_2_ib_apb_int (prevpayld_slave_2_ib_apb_int),    // slave_2_ib_apb_int
  .a_data_slave_2_ib_int (a_data_slave_2_ib_int),    // slave_2_ib_int
  .a_wpntr_gry_slave_2_ib_int (a_wpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .a_rpntr_bin_slave_2_ib_int (a_rpntr_bin_slave_2_ib_int),    // slave_2_ib_int
  .a_rpntr_gry_slave_2_ib_int (a_rpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .w_data_slave_2_ib_int (w_data_slave_2_ib_int),    // slave_2_ib_int
  .w_wpntr_gry_slave_2_ib_int (w_wpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .w_rpntr_bin_slave_2_ib_int (w_rpntr_bin_slave_2_ib_int),    // slave_2_ib_int
  .w_rpntr_gry_slave_2_ib_int (w_rpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .d_data_slave_2_ib_int (d_data_slave_2_ib_int),    // slave_2_ib_int
  .d_wpntr_gry_slave_2_ib_int (d_wpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .d_rpntr_bin_slave_2_ib_int (d_rpntr_bin_slave_2_ib_int),    // slave_2_ib_int
  .d_rpntr_gry_slave_2_ib_int (d_rpntr_gry_slave_2_ib_int),    // slave_2_ib_int
  .paddr_slave_3_ib_apb (paddr_slave_3_ib_apb),    // slave_3_ib_apb
  .pselx_slave_3_ib_apb (pselx_slave_3_ib_apb),    // slave_3_ib_apb
  .penable_slave_3_ib_apb (penable_slave_3_ib_apb),    // slave_3_ib_apb
  .pwrite_slave_3_ib_apb (pwrite_slave_3_ib_apb),    // slave_3_ib_apb
  .prdata_slave_3_ib_apb (prdata_slave_3_ib_apb),    // slave_3_ib_apb
  .pwdata_slave_3_ib_apb (pwdata_slave_3_ib_apb),    // slave_3_ib_apb
  .pready_slave_3_ib_apb (pready_slave_3_ib_apb),    // slave_3_ib_apb
  .pslverr_slave_3_ib_apb (pslverr_slave_3_ib_apb),    // slave_3_ib_apb
  .pack_slave_3_ib_apb_int (pack_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .preq_slave_3_ib_apb_int (preq_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .pfwdpayld_slave_3_ib_apb_int (pfwdpayld_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .prevpayld_slave_3_ib_apb_int (prevpayld_slave_3_ib_apb_int),    // slave_3_ib_apb_int
  .a_data_slave_3_ib_int (a_data_slave_3_ib_int),    // slave_3_ib_int
  .a_wpntr_gry_slave_3_ib_int (a_wpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .a_rpntr_bin_slave_3_ib_int (a_rpntr_bin_slave_3_ib_int),    // slave_3_ib_int
  .a_rpntr_gry_slave_3_ib_int (a_rpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .w_data_slave_3_ib_int (w_data_slave_3_ib_int),    // slave_3_ib_int
  .w_wpntr_gry_slave_3_ib_int (w_wpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .w_rpntr_bin_slave_3_ib_int (w_rpntr_bin_slave_3_ib_int),    // slave_3_ib_int
  .w_rpntr_gry_slave_3_ib_int (w_rpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .d_data_slave_3_ib_int (d_data_slave_3_ib_int),    // slave_3_ib_int
  .d_wpntr_gry_slave_3_ib_int (d_wpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .d_rpntr_bin_slave_3_ib_int (d_rpntr_bin_slave_3_ib_int),    // slave_3_ib_int
  .d_rpntr_gry_slave_3_ib_int (d_rpntr_gry_slave_3_ib_int),    // slave_3_ib_int
  .mainclk              (mainclk),    // usb3_m3_ib_apb
  .mainresetn           (mainresetn),    // usb3_m3_ib_apb
  .paddr_usb3_m3_ib_apb (paddr_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pselx_usb3_m3_ib_apb (pselx_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .penable_usb3_m3_ib_apb (penable_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pwrite_usb3_m3_ib_apb (pwrite_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .prdata_usb3_m3_ib_apb (prdata_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pwdata_usb3_m3_ib_apb (pwdata_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pready_usb3_m3_ib_apb (pready_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pslverr_usb3_m3_ib_apb (pslverr_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pack_usb3_m3_ib_apb_int (pack_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .preq_usb3_m3_ib_apb_int (preq_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .pfwdpayld_usb3_m3_ib_apb_int (pfwdpayld_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .prevpayld_usb3_m3_ib_apb_int (prevpayld_usb3_m3_ib_apb_int),    // usb3_m3_ib_apb_int
  .a_data_usb3_m3_ib_int (a_data_usb3_m3_ib_int),    // usb3_m3_ib_int
  .a_wpntr_gry_usb3_m3_ib_int (a_wpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .a_rpntr_bin_usb3_m3_ib_int (a_rpntr_bin_usb3_m3_ib_int),    // usb3_m3_ib_int
  .a_rpntr_gry_usb3_m3_ib_int (a_rpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_data_usb3_m3_ib_int (w_data_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_wpntr_gry_usb3_m3_ib_int (w_wpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_rpntr_bin_usb3_m3_ib_int (w_rpntr_bin_usb3_m3_ib_int),    // usb3_m3_ib_int
  .w_rpntr_gry_usb3_m3_ib_int (w_rpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_data_usb3_m3_ib_int (d_data_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_wpntr_gry_usb3_m3_ib_int (d_wpntr_gry_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_rpntr_bin_usb3_m3_ib_int (d_rpntr_bin_usb3_m3_ib_int),    // usb3_m3_ib_int
  .d_rpntr_gry_usb3_m3_ib_int (d_rpntr_gry_usb3_m3_ib_int)    // usb3_m3_ib_int
);


nic400_cd_main_r_peri_bus_r0p00     u_r_cd_main (
  .paddr_cpu2peri_s0_ib_apb (paddr_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pselx_cpu2peri_s0_ib_apb (pselx_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .penable_cpu2peri_s0_ib_apb (penable_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pwrite_cpu2peri_s0_ib_apb (pwrite_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .prdata_cpu2peri_s0_ib_apb (prdata_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pwdata_cpu2peri_s0_ib_apb (pwdata_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pready_cpu2peri_s0_ib_apb (pready_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .pslverr_cpu2peri_s0_ib_apb (pslverr_cpu2peri_s0_ib_apb),    // cpu2peri_s0_ib_apb
  .rsb_data_main_ml_m   (rsb_data_main_ml_m),    // main_ml_m
  .rsb_wptr_main_ml_m   (rsb_wptr_main_ml_m),    // main_ml_m
  .rsb_rptr_main_ml_m   (rsb_rptr_main_ml_m),    // main_ml_m
  .rsb_bin_rptr_main_ml_m (rsb_bin_rptr_main_ml_m),    // main_ml_m
  .rsb_data_main_ml_s   (rsb_data_main_ml_s),    // main_ml_s
  .rsb_wptr_main_ml_s   (rsb_wptr_main_ml_s),    // main_ml_s
  .rsb_rptr_main_ml_s   (rsb_rptr_main_ml_s),    // main_ml_s
  .rsb_bin_rptr_main_ml_s (rsb_bin_rptr_main_ml_s),    // main_ml_s
  .rsb_data_main_sl_m   (rsb_data_main_sl_m),    // main_sl_m
  .rsb_wptr_main_sl_m   (rsb_wptr_main_sl_m),    // main_sl_m
  .rsb_rptr_main_sl_m   (rsb_rptr_main_sl_m),    // main_sl_m
  .rsb_bin_rptr_main_sl_m (rsb_bin_rptr_main_sl_m),    // main_sl_m
  .rsb_data_main_sl_s   (rsb_data_main_sl_s),    // main_sl_s
  .rsb_wptr_main_sl_s   (rsb_wptr_main_sl_s),    // main_sl_s
  .rsb_rptr_main_sl_s   (rsb_rptr_main_sl_s),    // main_sl_s
  .rsb_bin_rptr_main_sl_s (rsb_bin_rptr_main_sl_s),    // main_sl_s
  .a_data_peri_gpv_ib1_int (a_data_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .a_valid_peri_gpv_ib1_int (a_valid_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .a_ready_peri_gpv_ib1_int (a_ready_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .w_data_peri_gpv_ib1_int (w_data_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .w_valid_peri_gpv_ib1_int (w_valid_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .w_ready_peri_gpv_ib1_int (w_ready_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .d_data_peri_gpv_ib1_int (d_data_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .d_valid_peri_gpv_ib1_int (d_valid_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .d_ready_peri_gpv_ib1_int (d_ready_peri_gpv_ib1_int),    // peri_gpv_ib1_int
  .paddr_slave_0_ib_apb (paddr_slave_0_ib_apb),    // slave_0_ib_apb
  .pselx_slave_0_ib_apb (pselx_slave_0_ib_apb),    // slave_0_ib_apb
  .penable_slave_0_ib_apb (penable_slave_0_ib_apb),    // slave_0_ib_apb
  .pwrite_slave_0_ib_apb (pwrite_slave_0_ib_apb),    // slave_0_ib_apb
  .prdata_slave_0_ib_apb (prdata_slave_0_ib_apb),    // slave_0_ib_apb
  .pwdata_slave_0_ib_apb (pwdata_slave_0_ib_apb),    // slave_0_ib_apb
  .pready_slave_0_ib_apb (pready_slave_0_ib_apb),    // slave_0_ib_apb
  .pslverr_slave_0_ib_apb (pslverr_slave_0_ib_apb),    // slave_0_ib_apb
  .paddr_slave_1_ib_apb (paddr_slave_1_ib_apb),    // slave_1_ib_apb
  .pselx_slave_1_ib_apb (pselx_slave_1_ib_apb),    // slave_1_ib_apb
  .penable_slave_1_ib_apb (penable_slave_1_ib_apb),    // slave_1_ib_apb
  .pwrite_slave_1_ib_apb (pwrite_slave_1_ib_apb),    // slave_1_ib_apb
  .prdata_slave_1_ib_apb (prdata_slave_1_ib_apb),    // slave_1_ib_apb
  .pwdata_slave_1_ib_apb (pwdata_slave_1_ib_apb),    // slave_1_ib_apb
  .pready_slave_1_ib_apb (pready_slave_1_ib_apb),    // slave_1_ib_apb
  .pslverr_slave_1_ib_apb (pslverr_slave_1_ib_apb),    // slave_1_ib_apb
  .paddr_slave_2_ib_apb (paddr_slave_2_ib_apb),    // slave_2_ib_apb
  .pselx_slave_2_ib_apb (pselx_slave_2_ib_apb),    // slave_2_ib_apb
  .penable_slave_2_ib_apb (penable_slave_2_ib_apb),    // slave_2_ib_apb
  .pwrite_slave_2_ib_apb (pwrite_slave_2_ib_apb),    // slave_2_ib_apb
  .prdata_slave_2_ib_apb (prdata_slave_2_ib_apb),    // slave_2_ib_apb
  .pwdata_slave_2_ib_apb (pwdata_slave_2_ib_apb),    // slave_2_ib_apb
  .pready_slave_2_ib_apb (pready_slave_2_ib_apb),    // slave_2_ib_apb
  .pslverr_slave_2_ib_apb (pslverr_slave_2_ib_apb),    // slave_2_ib_apb
  .paddr_slave_3_ib_apb (paddr_slave_3_ib_apb),    // slave_3_ib_apb
  .pselx_slave_3_ib_apb (pselx_slave_3_ib_apb),    // slave_3_ib_apb
  .penable_slave_3_ib_apb (penable_slave_3_ib_apb),    // slave_3_ib_apb
  .pwrite_slave_3_ib_apb (pwrite_slave_3_ib_apb),    // slave_3_ib_apb
  .prdata_slave_3_ib_apb (prdata_slave_3_ib_apb),    // slave_3_ib_apb
  .pwdata_slave_3_ib_apb (pwdata_slave_3_ib_apb),    // slave_3_ib_apb
  .pready_slave_3_ib_apb (pready_slave_3_ib_apb),    // slave_3_ib_apb
  .pslverr_slave_3_ib_apb (pslverr_slave_3_ib_apb),    // slave_3_ib_apb
  .mainclk_r            (mainclk_r),    // usb3_m3_ib_apb
  .mainresetn_r         (mainresetn_r),    // usb3_m3_ib_apb
  .paddr_usb3_m3_ib_apb (paddr_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pselx_usb3_m3_ib_apb (pselx_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .penable_usb3_m3_ib_apb (penable_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pwrite_usb3_m3_ib_apb (pwrite_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .prdata_usb3_m3_ib_apb (prdata_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pwdata_usb3_m3_ib_apb (pwdata_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pready_usb3_m3_ib_apb (pready_usb3_m3_ib_apb),    // usb3_m3_ib_apb
  .pslverr_usb3_m3_ib_apb (pslverr_usb3_m3_ib_apb)    // usb3_m3_ib_apb
);


nic400_rsb_connections_peri_bus_r0p00     u_rsb_conns (
  .rsb_data_main_master_m (rsb_data_main_ml_s),    // main_master_m
  .rsb_wptr_main_master_m (rsb_wptr_main_ml_s),    // main_master_m
  .rsb_rptr_main_master_m (rsb_rptr_main_ml_s),    // main_master_m
  .rsb_b_rptr_main_master_m (rsb_bin_rptr_main_ml_s),    // main_master_m
  .rsb_data_main_master_s (rsb_data_main_ml_m),    // main_master_s
  .rsb_wptr_main_master_s (rsb_wptr_main_ml_m),    // main_master_s
  .rsb_rptr_main_master_s (rsb_rptr_main_ml_m),    // main_master_s
  .rsb_b_rptr_main_master_s (rsb_bin_rptr_main_ml_m),    // main_master_s
  .rsb_data_main_slave_m (rsb_data_main_sl_s),    // main_slave_m
  .rsb_wptr_main_slave_m (rsb_wptr_main_sl_s),    // main_slave_m
  .rsb_rptr_main_slave_m (rsb_rptr_main_sl_s),    // main_slave_m
  .rsb_b_rptr_main_slave_m (rsb_bin_rptr_main_sl_s),    // main_slave_m
  .rsb_data_main_slave_s (rsb_data_main_sl_m),    // main_slave_s
  .rsb_wptr_main_slave_s (rsb_wptr_main_sl_m),    // main_slave_s
  .rsb_rptr_main_slave_s (rsb_rptr_main_sl_m),    // main_slave_s
  .rsb_b_rptr_main_slave_s (rsb_bin_rptr_main_sl_m)    // main_slave_s
);



endmodule
