//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// The confidential and proprietary information contained in this file may     
// only be used by a person authorised under and to the extent permitted       
// by a subsisting licensing agreement from ARM Limited.                       
//                                                                             
//            (C) COPYRIGHT 2005-2015 ARM Limited.
//                ALL RIGHTS RESERVED                                          
//                                                                             
// This entire notice must be reproduced on all copies of this file            
// and copies of this file may only be made by a person if such person is      
// permitted to do so under the terms of a subsisting license agreement        
// from ARM Limited.                                                           
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Top-Level Verilog file is auto-generated by AMBA Designer ADr3p5-01eac0-build-0005

//                                                                             
// Stitcher: generic_stitcher_core v3.1, built on Dec  1 2015
//                                                                             
// Filename: nic400_wn7_peri_r0p21.v
// Created : Thu Oct 18 17:15:56 2018                            
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Generated with Validator version1.0


//-----------------------------------------------------------------------------
// Module Declaration nic400_wn7_peri_r0p21
//-----------------------------------------------------------------------------

module bus_peri (

  aud_clk,
  aud_clken,
  aud_resetn,
  dma_isp_clk,
  dma_isp_clken,
  dma_isp_resetn,
  cpu2periclk,
  cpu2periresetn,
  dsp2periclk,
  dsp2periresetn,
  mainclk,
  mainclk_r,
  mainresetn,
  mainresetn_r,

// Instance: u_cd_aud, Port: aud_m9

  paddr_aud_m9,
  pselx_aud_m9,
  penable_aud_m9,
  pwrite_aud_m9,
  prdata_aud_m9,
  pwdata_aud_m9,
  pready_aud_m9,
  pslverr_aud_m9,

// Instance: u_cd_dma_isp, Port: dma_isp_m0
  haddr_dma_isp_m0,
  hburst_dma_isp_m0,
  hprot_dma_isp_m0,
  hsize_dma_isp_m0,
  htrans_dma_isp_m0,
  hwdata_dma_isp_m0,
  hwrite_dma_isp_m0,
  hrdata_dma_isp_m0,
  hreadyout_dma_isp_m0,
  hresp_dma_isp_m0,
  hselx_dma_isp_m0,
  hready_dma_isp_m0,
 
// Instance: u_cd_cpu2peri, Port: cpu2peri_s0

  awid_cpu2peri_s0,
  awaddr_cpu2peri_s0,
  awlen_cpu2peri_s0,
  awsize_cpu2peri_s0,
  awburst_cpu2peri_s0,
  awlock_cpu2peri_s0,
  awcache_cpu2peri_s0,
  awprot_cpu2peri_s0,
  awvalid_cpu2peri_s0,
  awready_cpu2peri_s0,
  wdata_cpu2peri_s0,
  wstrb_cpu2peri_s0,
  wlast_cpu2peri_s0,
  wvalid_cpu2peri_s0,
  wready_cpu2peri_s0,
  bid_cpu2peri_s0,
  bresp_cpu2peri_s0,
  bvalid_cpu2peri_s0,
  bready_cpu2peri_s0,
  arid_cpu2peri_s0,
  araddr_cpu2peri_s0,
  arlen_cpu2peri_s0,
  arsize_cpu2peri_s0,
  arburst_cpu2peri_s0,
  arlock_cpu2peri_s0,
  arcache_cpu2peri_s0,
  arprot_cpu2peri_s0,
  arvalid_cpu2peri_s0,
  arready_cpu2peri_s0,
  rid_cpu2peri_s0,
  rdata_cpu2peri_s0,
  rresp_cpu2peri_s0,
  rlast_cpu2peri_s0,
  rvalid_cpu2peri_s0,
  rready_cpu2peri_s0
  
 
);



//-----------------------------------------------------------------------------
// Port Declarations
//-----------------------------------------------------------------------------


// Instance: u_cd_aud, Port: aud_m9

output [31:0] paddr_aud_m9;
output        pselx_aud_m9;
output        penable_aud_m9;
output        pwrite_aud_m9;
input  [31:0] prdata_aud_m9;
output [31:0] pwdata_aud_m9;
input         pready_aud_m9;
input         pslverr_aud_m9;

// Instance: u_cd_dma_isp, Port: dma_isp_m0

output [31:0] haddr_dma_isp_m0;
output [2:0]  hburst_dma_isp_m0;
output [3:0]  hprot_dma_isp_m0;
output [2:0]  hsize_dma_isp_m0;
output [1:0]  htrans_dma_isp_m0;
output [31:0] hwdata_dma_isp_m0;
output        hwrite_dma_isp_m0;
input  [31:0] hrdata_dma_isp_m0;
input         hreadyout_dma_isp_m0;
input         hresp_dma_isp_m0;
output        hselx_dma_isp_m0;
output        hready_dma_isp_m0;

// Instance: u_cd_cpu2peri, Port: cpu2peri_s0

input  [11:0] awid_cpu2peri_s0;
input  [31:0] awaddr_cpu2peri_s0;
input  [7:0]  awlen_cpu2peri_s0;
input  [2:0]  awsize_cpu2peri_s0;
input  [1:0]  awburst_cpu2peri_s0;
input         awlock_cpu2peri_s0;
input  [3:0]  awcache_cpu2peri_s0;
input  [2:0]  awprot_cpu2peri_s0;
input         awvalid_cpu2peri_s0;
output        awready_cpu2peri_s0;
input  [31:0] wdata_cpu2peri_s0;
input  [3:0]  wstrb_cpu2peri_s0;
input         wlast_cpu2peri_s0;
input         wvalid_cpu2peri_s0;
output        wready_cpu2peri_s0;
output [11:0] bid_cpu2peri_s0;
output [1:0]  bresp_cpu2peri_s0;
output        bvalid_cpu2peri_s0;
input         bready_cpu2peri_s0;
input  [11:0] arid_cpu2peri_s0;
input  [31:0] araddr_cpu2peri_s0;
input  [7:0]  arlen_cpu2peri_s0;
input  [2:0]  arsize_cpu2peri_s0;
input  [1:0]  arburst_cpu2peri_s0;
input         arlock_cpu2peri_s0;
input  [3:0]  arcache_cpu2peri_s0;
input  [2:0]  arprot_cpu2peri_s0;
input         arvalid_cpu2peri_s0;
output        arready_cpu2peri_s0;
output [11:0] rid_cpu2peri_s0;
output [31:0] rdata_cpu2peri_s0;
output [1:0]  rresp_cpu2peri_s0;
output        rlast_cpu2peri_s0;
output        rvalid_cpu2peri_s0;
input         rready_cpu2peri_s0;

//  Non-bus signals

input         aud_clk;
input         aud_clken;
input         aud_resetn;
input         dma_isp_clk;
input         dma_isp_clken;
input         dma_isp_resetn;
input         cpu2periclk;
input         cpu2periresetn;
input         dsp2periclk;
input         dsp2periresetn;
input         mainclk;
input         mainclk_r;
input         mainresetn;
input         mainresetn_r;


endmodule
