//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// The confidential and proprietary information contained in this file may     
// only be used by a person authorised under and to the extent permitted       
// by a subsisting licensing agreement from ARM Limited.                       
//                                                                             
//            (C) COPYRIGHT 2005-2015 ARM Limited.
//                ALL RIGHTS RESERVED                                          
//                                                                             
// This entire notice must be reproduced on all copies of this file            
// and copies of this file may only be made by a person if such person is      
// permitted to do so under the terms of a subsisting license agreement        
// from ARM Limited.                                                           
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Top-Level Verilog file is auto-generated by AMBA Designer ADr3p5-01eac0-build-0005

//                                                                             
// Stitcher: generic_stitcher_core v3.1, built on Dec  1 2015
//                                                                             
// Filename: nic400_hsp_bus_r0p00.v
// Created : Tue Jul 4 00:55:26 2017                            
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Generated with Validator version1.0


//-----------------------------------------------------------------------------
// Module Declaration nic400_hsp_bus_r0p00
//-----------------------------------------------------------------------------

module nic400_hsp_bus_r0p00 (
  
// Instance: u_cd_dvp, Port: dvp_s1

  awid_dvp_s1,
  awaddr_dvp_s1,
  awlen_dvp_s1,
  awsize_dvp_s1,
  awburst_dvp_s1,
  awlock_dvp_s1,
  awcache_dvp_s1,
  awprot_dvp_s1,
  awvalid_dvp_s1,
  awready_dvp_s1,
  wdata_dvp_s1,
  wstrb_dvp_s1,
  wlast_dvp_s1,
  wvalid_dvp_s1,
  wready_dvp_s1,
  bid_dvp_s1,
  bresp_dvp_s1,
  bvalid_dvp_s1,
  bready_dvp_s1,
  arid_dvp_s1,
  araddr_dvp_s1,
  arlen_dvp_s1,
  arsize_dvp_s1,
  arburst_dvp_s1,
  arlock_dvp_s1,
  arcache_dvp_s1,
  arprot_dvp_s1,
  arvalid_dvp_s1,
  arready_dvp_s1,
  rid_dvp_s1,
  rdata_dvp_s1,
  rresp_dvp_s1,
  rlast_dvp_s1,
  rvalid_dvp_s1,
  rready_dvp_s1,
  
// Instance: u_cd_hsp_gpv, Port: hsp_gpv_s3

  haddr_hsp_gpv_s3,
  hburst_hsp_gpv_s3,
  hprot_hsp_gpv_s3,
  hsize_hsp_gpv_s3,
  htrans_hsp_gpv_s3,
  hwdata_hsp_gpv_s3,
  hwrite_hsp_gpv_s3,
  hrdata_hsp_gpv_s3,
  hresp_hsp_gpv_s3,
  hready_hsp_gpv_s3,
  
// Instance: u_cd_keti, Port: keti_s2

  awid_keti_s2,
  awaddr_keti_s2,
  awlen_keti_s2,
  awsize_keti_s2,
  awburst_keti_s2,
  awlock_keti_s2,
  awcache_keti_s2,
  awprot_keti_s2,
  awvalid_keti_s2,
  awready_keti_s2,
  wdata_keti_s2,
  wstrb_keti_s2,
  wlast_keti_s2,
  wvalid_keti_s2,
  wready_keti_s2,
  bid_keti_s2,
  bresp_keti_s2,
  bvalid_keti_s2,
  bready_keti_s2,
  arid_keti_s2,
  araddr_keti_s2,
  arlen_keti_s2,
  arsize_keti_s2,
  arburst_keti_s2,
  arlock_keti_s2,
  arcache_keti_s2,
  arprot_keti_s2,
  arvalid_keti_s2,
  arready_keti_s2,
  rid_keti_s2,
  rdata_keti_s2,
  rresp_keti_s2,
  rlast_keti_s2,
  rvalid_keti_s2,
  rready_keti_s2,
  
// Instance: u_cd_main, Port: hsp2main_m0

  awid_hsp2main_m0,
  awaddr_hsp2main_m0,
  awlen_hsp2main_m0,
  awsize_hsp2main_m0,
  awburst_hsp2main_m0,
  awlock_hsp2main_m0,
  awcache_hsp2main_m0,
  awprot_hsp2main_m0,
  awvalid_hsp2main_m0,
  awready_hsp2main_m0,
  wdata_hsp2main_m0,
  wstrb_hsp2main_m0,
  wlast_hsp2main_m0,
  wvalid_hsp2main_m0,
  wready_hsp2main_m0,
  bid_hsp2main_m0,
  bresp_hsp2main_m0,
  bvalid_hsp2main_m0,
  bready_hsp2main_m0,
  arid_hsp2main_m0,
  araddr_hsp2main_m0,
  arlen_hsp2main_m0,
  arsize_hsp2main_m0,
  arburst_hsp2main_m0,
  arlock_hsp2main_m0,
  arcache_hsp2main_m0,
  arprot_hsp2main_m0,
  arvalid_hsp2main_m0,
  arready_hsp2main_m0,
  rid_hsp2main_m0,
  rdata_hsp2main_m0,
  rresp_hsp2main_m0,
  rlast_hsp2main_m0,
  rvalid_hsp2main_m0,
  rready_hsp2main_m0,
  
// Instance: u_cd_usb3, Port: usb3_s0

  awid_usb3_s0,
  awaddr_usb3_s0,
  awlen_usb3_s0,
  awsize_usb3_s0,
  awburst_usb3_s0,
  awlock_usb3_s0,
  awcache_usb3_s0,
  awprot_usb3_s0,
  awvalid_usb3_s0,
  awready_usb3_s0,
  wdata_usb3_s0,
  wstrb_usb3_s0,
  wlast_usb3_s0,
  wvalid_usb3_s0,
  wready_usb3_s0,
  bid_usb3_s0,
  bresp_usb3_s0,
  bvalid_usb3_s0,
  bready_usb3_s0,
  arid_usb3_s0,
  araddr_usb3_s0,
  arlen_usb3_s0,
  arsize_usb3_s0,
  arburst_usb3_s0,
  arlock_usb3_s0,
  arcache_usb3_s0,
  arprot_usb3_s0,
  arvalid_usb3_s0,
  arready_usb3_s0,
  rid_usb3_s0,
  rdata_usb3_s0,
  rresp_usb3_s0,
  rlast_usb3_s0,
  rvalid_usb3_s0,
  rready_usb3_s0,

//  Non-bus signals

  dvpclk,
  dvpresetn,
  hsp_gpvclk,
  hsp_gpvresetn,
  keticlk,
  ketiresetn,
  mainclk,
  mainclk_r,
  mainresetn,
  mainresetn_r,
  usb3clk,
  usb3resetn

);



//-----------------------------------------------------------------------------
// Port Declarations
//-----------------------------------------------------------------------------


// Instance: u_cd_dvp, Port: dvp_s1

input  [2:0]  awid_dvp_s1;
input  [31:0] awaddr_dvp_s1;
input  [7:0]  awlen_dvp_s1;
input  [2:0]  awsize_dvp_s1;
input  [1:0]  awburst_dvp_s1;
input         awlock_dvp_s1;
input  [3:0]  awcache_dvp_s1;
input  [2:0]  awprot_dvp_s1;
input         awvalid_dvp_s1;
output        awready_dvp_s1;
input  [127:0] wdata_dvp_s1;
input  [15:0] wstrb_dvp_s1;
input         wlast_dvp_s1;
input         wvalid_dvp_s1;
output        wready_dvp_s1;
output [2:0]  bid_dvp_s1;
output [1:0]  bresp_dvp_s1;
output        bvalid_dvp_s1;
input         bready_dvp_s1;
input  [2:0]  arid_dvp_s1;
input  [31:0] araddr_dvp_s1;
input  [7:0]  arlen_dvp_s1;
input  [2:0]  arsize_dvp_s1;
input  [1:0]  arburst_dvp_s1;
input         arlock_dvp_s1;
input  [3:0]  arcache_dvp_s1;
input  [2:0]  arprot_dvp_s1;
input         arvalid_dvp_s1;
output        arready_dvp_s1;
output [2:0]  rid_dvp_s1;
output [127:0] rdata_dvp_s1;
output [1:0]  rresp_dvp_s1;
output        rlast_dvp_s1;
output        rvalid_dvp_s1;
input         rready_dvp_s1;

// Instance: u_cd_hsp_gpv, Port: hsp_gpv_s3

input  [31:0] haddr_hsp_gpv_s3;
input  [2:0]  hburst_hsp_gpv_s3;
input  [3:0]  hprot_hsp_gpv_s3;
input  [2:0]  hsize_hsp_gpv_s3;
input  [1:0]  htrans_hsp_gpv_s3;
input  [31:0] hwdata_hsp_gpv_s3;
input         hwrite_hsp_gpv_s3;
output [31:0] hrdata_hsp_gpv_s3;
output        hresp_hsp_gpv_s3;
output        hready_hsp_gpv_s3;

// Instance: u_cd_keti, Port: keti_s2

input  [2:0]  awid_keti_s2;
input  [31:0] awaddr_keti_s2;
input  [7:0]  awlen_keti_s2;
input  [2:0]  awsize_keti_s2;
input  [1:0]  awburst_keti_s2;
input         awlock_keti_s2;
input  [3:0]  awcache_keti_s2;
input  [2:0]  awprot_keti_s2;
input         awvalid_keti_s2;
output        awready_keti_s2;
input  [127:0] wdata_keti_s2;
input  [15:0] wstrb_keti_s2;
input         wlast_keti_s2;
input         wvalid_keti_s2;
output        wready_keti_s2;
output [2:0]  bid_keti_s2;
output [1:0]  bresp_keti_s2;
output        bvalid_keti_s2;
input         bready_keti_s2;
input  [2:0]  arid_keti_s2;
input  [31:0] araddr_keti_s2;
input  [7:0]  arlen_keti_s2;
input  [2:0]  arsize_keti_s2;
input  [1:0]  arburst_keti_s2;
input         arlock_keti_s2;
input  [3:0]  arcache_keti_s2;
input  [2:0]  arprot_keti_s2;
input         arvalid_keti_s2;
output        arready_keti_s2;
output [2:0]  rid_keti_s2;
output [127:0] rdata_keti_s2;
output [1:0]  rresp_keti_s2;
output        rlast_keti_s2;
output        rvalid_keti_s2;
input         rready_keti_s2;

// Instance: u_cd_main, Port: hsp2main_m0

output [5:0]  awid_hsp2main_m0;
output [31:0] awaddr_hsp2main_m0;
output [7:0]  awlen_hsp2main_m0;
output [2:0]  awsize_hsp2main_m0;
output [1:0]  awburst_hsp2main_m0;
output        awlock_hsp2main_m0;
output [3:0]  awcache_hsp2main_m0;
output [2:0]  awprot_hsp2main_m0;
output        awvalid_hsp2main_m0;
input         awready_hsp2main_m0;
output [31:0] wdata_hsp2main_m0;
output [3:0]  wstrb_hsp2main_m0;
output        wlast_hsp2main_m0;
output        wvalid_hsp2main_m0;
input         wready_hsp2main_m0;
input  [5:0]  bid_hsp2main_m0;
input  [1:0]  bresp_hsp2main_m0;
input         bvalid_hsp2main_m0;
output        bready_hsp2main_m0;
output [5:0]  arid_hsp2main_m0;
output [31:0] araddr_hsp2main_m0;
output [7:0]  arlen_hsp2main_m0;
output [2:0]  arsize_hsp2main_m0;
output [1:0]  arburst_hsp2main_m0;
output        arlock_hsp2main_m0;
output [3:0]  arcache_hsp2main_m0;
output [2:0]  arprot_hsp2main_m0;
output        arvalid_hsp2main_m0;
input         arready_hsp2main_m0;
input  [5:0]  rid_hsp2main_m0;
input  [31:0] rdata_hsp2main_m0;
input  [1:0]  rresp_hsp2main_m0;
input         rlast_hsp2main_m0;
input         rvalid_hsp2main_m0;
output        rready_hsp2main_m0;

// Instance: u_cd_usb3, Port: usb3_s0

input  [3:0]  awid_usb3_s0;
input  [31:0] awaddr_usb3_s0;
input  [7:0]  awlen_usb3_s0;
input  [2:0]  awsize_usb3_s0;
input  [1:0]  awburst_usb3_s0;
input         awlock_usb3_s0;
input  [3:0]  awcache_usb3_s0;
input  [2:0]  awprot_usb3_s0;
input         awvalid_usb3_s0;
output        awready_usb3_s0;
input  [127:0] wdata_usb3_s0;
input  [15:0] wstrb_usb3_s0;
input         wlast_usb3_s0;
input         wvalid_usb3_s0;
output        wready_usb3_s0;
output [3:0]  bid_usb3_s0;
output [1:0]  bresp_usb3_s0;
output        bvalid_usb3_s0;
input         bready_usb3_s0;
input  [3:0]  arid_usb3_s0;
input  [31:0] araddr_usb3_s0;
input  [7:0]  arlen_usb3_s0;
input  [2:0]  arsize_usb3_s0;
input  [1:0]  arburst_usb3_s0;
input         arlock_usb3_s0;
input  [3:0]  arcache_usb3_s0;
input  [2:0]  arprot_usb3_s0;
input         arvalid_usb3_s0;
output        arready_usb3_s0;
output [3:0]  rid_usb3_s0;
output [127:0] rdata_usb3_s0;
output [1:0]  rresp_usb3_s0;
output        rlast_usb3_s0;
output        rvalid_usb3_s0;
input         rready_usb3_s0;

//  Non-bus signals

input         dvpclk;
input         dvpresetn;
input         hsp_gpvclk;
input         hsp_gpvresetn;
input         keticlk;
input         ketiresetn;
input         mainclk;
input         mainclk_r;
input         mainresetn;
input         mainresetn_r;
input         usb3clk;
input         usb3resetn;



//-----------------------------------------------------------------------------
// Internal Wire Declarations
//-----------------------------------------------------------------------------

wire   [31:0]  araddr_hsp2main_m0;
wire   [1:0]   arburst_hsp2main_m0;
wire   [3:0]   arcache_hsp2main_m0;
wire   [5:0]   arid_hsp2main_m0;
wire   [7:0]   arlen_hsp2main_m0;
wire           arlock_hsp2main_m0;
wire   [2:0]   arprot_hsp2main_m0;
wire           arready_dvp_s1;
wire           arready_keti_s2;
wire           arready_usb3_s0;
wire   [2:0]   arsize_hsp2main_m0;
wire           arvalid_hsp2main_m0;
wire   [31:0]  awaddr_hsp2main_m0;
wire   [1:0]   awburst_hsp2main_m0;
wire   [3:0]   awcache_hsp2main_m0;
wire   [5:0]   awid_hsp2main_m0;
wire   [7:0]   awlen_hsp2main_m0;
wire           awlock_hsp2main_m0;
wire   [2:0]   awprot_hsp2main_m0;
wire           awready_dvp_s1;
wire           awready_keti_s2;
wire           awready_usb3_s0;
wire   [2:0]   awsize_hsp2main_m0;
wire           awvalid_hsp2main_m0;
wire   [2:0]   bid_dvp_s1;
wire   [2:0]   bid_keti_s2;
wire   [3:0]   bid_usb3_s0;
wire           bready_hsp2main_m0;
wire   [1:0]   bresp_dvp_s1;
wire   [1:0]   bresp_keti_s2;
wire   [1:0]   bresp_usb3_s0;
wire           bvalid_dvp_s1;
wire           bvalid_keti_s2;
wire           bvalid_usb3_s0;
wire   [31:0]  hrdata_hsp_gpv_s3;
wire           hready_hsp_gpv_s3;
wire           hresp_hsp_gpv_s3;
wire   [127:0] rdata_dvp_s1;
wire   [127:0] rdata_keti_s2;
wire   [127:0] rdata_usb3_s0;
wire   [2:0]   rid_dvp_s1;
wire   [2:0]   rid_keti_s2;
wire   [3:0]   rid_usb3_s0;
wire           rlast_dvp_s1;
wire           rlast_keti_s2;
wire           rlast_usb3_s0;
wire           rready_hsp2main_m0;
wire   [1:0]   rresp_dvp_s1;
wire   [1:0]   rresp_keti_s2;
wire   [1:0]   rresp_usb3_s0;
wire           rvalid_dvp_s1;
wire           rvalid_keti_s2;
wire           rvalid_usb3_s0;
wire   [31:0]  wdata_hsp2main_m0;
wire           wlast_hsp2main_m0;
wire           wready_dvp_s1;
wire           wready_keti_s2;
wire           wready_usb3_s0;
wire   [3:0]   wstrb_hsp2main_m0;
wire           wvalid_hsp2main_m0;
wire   [57:0]  ar_data_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [2:0]   ar_wpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [57:0]  aw_data_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [2:0]   aw_wpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [1:0]   b_rpntr_bin_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [2:0]   b_rpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire           pack_dvp_s1_ib_apb_int;    //dvp_s1_ib_apb_int - u_cd_dvp
wire   [32:0]  prevpayld_dvp_s1_ib_apb_int;    //dvp_s1_ib_apb_int - u_cd_dvp
wire   [2:0]   r_rpntr_bin_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [3:0]   r_rpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [144:0] w_data_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [3:0]   w_wpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_dvp
wire   [55:0]  a_data_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_hsp_gpv
wire   [1:0]   a_wpntr_gry_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_hsp_gpv
wire           d_rpntr_bin_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_hsp_gpv
wire   [1:0]   d_rpntr_gry_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_hsp_gpv
wire           pack_hsp_gpv_s3_ib_apb_int;    //hsp_gpv_s3_ib_apb_int - u_cd_hsp_gpv
wire   [32:0]  prevpayld_hsp_gpv_s3_ib_apb_int;    //hsp_gpv_s3_ib_apb_int - u_cd_hsp_gpv
wire   [144:0] w_data_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_hsp_gpv
wire   [1:0]   w_wpntr_gry_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_hsp_gpv
wire   [57:0]  ar_data_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [2:0]   ar_wpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [57:0]  aw_data_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [2:0]   aw_wpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [1:0]   b_rpntr_bin_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [2:0]   b_rpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire           pack_keti_s2_ib_apb_int;    //keti_s2_ib_apb_int - u_cd_keti
wire   [32:0]  prevpayld_keti_s2_ib_apb_int;    //keti_s2_ib_apb_int - u_cd_keti
wire   [2:0]   r_rpntr_bin_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [3:0]   r_rpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [144:0] w_data_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [3:0]   w_wpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_keti
wire   [74:0]  a_data_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_cd_main
wire           a_rpntr_bin_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_main
wire   [1:0]   a_rpntr_gry_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_main
wire           a_valid_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_cd_main
wire   [1:0]   ar_rpntr_bin_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [1:0]   ar_rpntr_bin_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [1:0]   ar_rpntr_bin_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [2:0]   ar_rpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [2:0]   ar_rpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [2:0]   ar_rpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [1:0]   aw_rpntr_bin_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [1:0]   aw_rpntr_bin_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [1:0]   aw_rpntr_bin_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [2:0]   aw_rpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [2:0]   aw_rpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [2:0]   aw_rpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [4:0]   b_data_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [4:0]   b_data_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [5:0]   b_data_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [2:0]   b_wpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [2:0]   b_wpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [2:0]   b_wpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [131:0] d_data_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_main
wire           d_ready_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_cd_main
wire   [1:0]   d_wpntr_gry_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_main
wire   [71:0]  pfwdpayld_dvp_s1_ib_apb_int;    //dvp_s1_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_hsp_gpv_s3_ib_apb_int;    //hsp_gpv_s3_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_keti_s2_ib_apb_int;    //keti_s2_ib_apb_int - u_cd_main
wire   [71:0]  pfwdpayld_usb3_s0_ib_apb_int;    //usb3_s0_ib_apb_int - u_cd_main
wire   [31:0]  prdata_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_cd_main
wire   [31:0]  prdata_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_cd_main
wire   [31:0]  prdata_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_cd_main
wire   [31:0]  prdata_keti_s2_ib_apb;    //keti_s2_ib_apb - u_cd_main
wire   [31:0]  prdata_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_cd_main
wire           pready_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_cd_main
wire           pready_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_cd_main
wire           pready_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_cd_main
wire           pready_keti_s2_ib_apb;    //keti_s2_ib_apb - u_cd_main
wire           pready_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_cd_main
wire           preq_dvp_s1_ib_apb_int;    //dvp_s1_ib_apb_int - u_cd_main
wire           preq_hsp_gpv_s3_ib_apb_int;    //hsp_gpv_s3_ib_apb_int - u_cd_main
wire           preq_keti_s2_ib_apb_int;    //keti_s2_ib_apb_int - u_cd_main
wire           preq_usb3_s0_ib_apb_int;    //usb3_s0_ib_apb_int - u_cd_main
wire           pslverr_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_cd_main
wire           pslverr_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_cd_main
wire           pslverr_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_cd_main
wire           pslverr_keti_s2_ib_apb;    //keti_s2_ib_apb - u_cd_main
wire           pslverr_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_cd_main
wire   [133:0] r_data_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [133:0] r_data_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [134:0] r_data_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [3:0]   r_wpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [3:0]   r_wpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [3:0]   r_wpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [144:0] w_data_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_cd_main
wire   [2:0]   w_rpntr_bin_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire           w_rpntr_bin_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_main
wire   [2:0]   w_rpntr_bin_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [2:0]   w_rpntr_bin_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire   [3:0]   w_rpntr_gry_dvp_s1_ib_int;    //dvp_s1_ib_int - u_cd_main
wire   [1:0]   w_rpntr_gry_hsp_gpv_s3_ib_int;    //hsp_gpv_s3_ib_int - u_cd_main
wire   [3:0]   w_rpntr_gry_keti_s2_ib_int;    //keti_s2_ib_int - u_cd_main
wire   [3:0]   w_rpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_main
wire           w_valid_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_cd_main
wire   [58:0]  ar_data_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [2:0]   ar_wpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [58:0]  aw_data_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [2:0]   aw_wpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [1:0]   b_rpntr_bin_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [2:0]   b_rpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire           pack_usb3_s0_ib_apb_int;    //usb3_s0_ib_apb_int - u_cd_usb3
wire   [32:0]  prevpayld_usb3_s0_ib_apb_int;    //usb3_s0_ib_apb_int - u_cd_usb3
wire   [2:0]   r_rpntr_bin_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [3:0]   r_rpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [144:0] w_data_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire   [3:0]   w_wpntr_gry_usb3_s0_ib_int;    //usb3_s0_ib_int - u_cd_usb3
wire           a_ready_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_r_cd_main
wire   [139:0] d_data_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_r_cd_main
wire           d_valid_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_r_cd_main
wire   [31:0]  paddr_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_r_cd_main
wire   [31:0]  paddr_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_r_cd_main
wire   [31:0]  paddr_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_r_cd_main
wire   [31:0]  paddr_keti_s2_ib_apb;    //keti_s2_ib_apb - u_r_cd_main
wire   [31:0]  paddr_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_r_cd_main
wire           penable_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_r_cd_main
wire           penable_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_r_cd_main
wire           penable_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_r_cd_main
wire           penable_keti_s2_ib_apb;    //keti_s2_ib_apb - u_r_cd_main
wire           penable_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_r_cd_main
wire           pselx_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_r_cd_main
wire           pselx_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_r_cd_main
wire           pselx_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_r_cd_main
wire           pselx_keti_s2_ib_apb;    //keti_s2_ib_apb - u_r_cd_main
wire           pselx_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_keti_s2_ib_apb;    //keti_s2_ib_apb - u_r_cd_main
wire   [31:0]  pwdata_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_r_cd_main
wire           pwrite_dvp_s1_ib_apb;    //dvp_s1_ib_apb - u_r_cd_main
wire           pwrite_hsp2main_m0_ib_apb;    //hsp2main_m0_ib_apb - u_r_cd_main
wire           pwrite_hsp_gpv_s3_ib_apb;    //hsp_gpv_s3_ib_apb - u_r_cd_main
wire           pwrite_keti_s2_ib_apb;    //keti_s2_ib_apb - u_r_cd_main
wire           pwrite_usb3_s0_ib_apb;    //usb3_s0_ib_apb - u_r_cd_main
wire   [1:0]   rsb_bin_rptr_main_ml_s;    //main_ml_s - u_r_cd_main
wire   [1:0]   rsb_bin_rptr_main_sl_s;    //main_sl_s - u_r_cd_main
wire   [7:0]   rsb_data_main_ml_m;    //main_ml_m - u_r_cd_main
wire   [7:0]   rsb_data_main_sl_m;    //main_sl_m - u_r_cd_main
wire   [2:0]   rsb_rptr_main_ml_s;    //main_ml_s - u_r_cd_main
wire   [2:0]   rsb_rptr_main_sl_s;    //main_sl_s - u_r_cd_main
wire   [2:0]   rsb_wptr_main_ml_m;    //main_ml_m - u_r_cd_main
wire   [2:0]   rsb_wptr_main_sl_m;    //main_sl_m - u_r_cd_main
wire           w_ready_hsp_gpv_ib1_int;    //hsp_gpv_ib1_int - u_r_cd_main
wire   [1:0]   rsb_bin_rptr_main_ml_m;    //main_master_s - u_rsb_conns
wire   [1:0]   rsb_bin_rptr_main_sl_m;    //main_slave_s - u_rsb_conns
wire   [7:0]   rsb_data_main_ml_s;    //main_master_m - u_rsb_conns
wire   [7:0]   rsb_data_main_sl_s;    //main_slave_m - u_rsb_conns
wire   [2:0]   rsb_rptr_main_ml_m;    //main_master_s - u_rsb_conns
wire   [2:0]   rsb_rptr_main_sl_m;    //main_slave_s - u_rsb_conns
wire   [2:0]   rsb_wptr_main_ml_s;    //main_master_m - u_rsb_conns
wire   [2:0]   rsb_wptr_main_sl_s;    //main_slave_m - u_rsb_conns
wire   [31:0]  araddr_dvp_s1;
wire   [31:0]  araddr_keti_s2;
wire   [31:0]  araddr_usb3_s0;
wire   [1:0]   arburst_dvp_s1;
wire   [1:0]   arburst_keti_s2;
wire   [1:0]   arburst_usb3_s0;
wire   [3:0]   arcache_dvp_s1;
wire   [3:0]   arcache_keti_s2;
wire   [3:0]   arcache_usb3_s0;
wire   [2:0]   arid_dvp_s1;
wire   [2:0]   arid_keti_s2;
wire   [3:0]   arid_usb3_s0;
wire   [7:0]   arlen_dvp_s1;
wire   [7:0]   arlen_keti_s2;
wire   [7:0]   arlen_usb3_s0;
wire           arlock_dvp_s1;
wire           arlock_keti_s2;
wire           arlock_usb3_s0;
wire   [2:0]   arprot_dvp_s1;
wire   [2:0]   arprot_keti_s2;
wire   [2:0]   arprot_usb3_s0;
wire           arready_hsp2main_m0;
wire   [2:0]   arsize_dvp_s1;
wire   [2:0]   arsize_keti_s2;
wire   [2:0]   arsize_usb3_s0;
wire           arvalid_dvp_s1;
wire           arvalid_keti_s2;
wire           arvalid_usb3_s0;
wire   [31:0]  awaddr_dvp_s1;
wire   [31:0]  awaddr_keti_s2;
wire   [31:0]  awaddr_usb3_s0;
wire   [1:0]   awburst_dvp_s1;
wire   [1:0]   awburst_keti_s2;
wire   [1:0]   awburst_usb3_s0;
wire   [3:0]   awcache_dvp_s1;
wire   [3:0]   awcache_keti_s2;
wire   [3:0]   awcache_usb3_s0;
wire   [2:0]   awid_dvp_s1;
wire   [2:0]   awid_keti_s2;
wire   [3:0]   awid_usb3_s0;
wire   [7:0]   awlen_dvp_s1;
wire   [7:0]   awlen_keti_s2;
wire   [7:0]   awlen_usb3_s0;
wire           awlock_dvp_s1;
wire           awlock_keti_s2;
wire           awlock_usb3_s0;
wire   [2:0]   awprot_dvp_s1;
wire   [2:0]   awprot_keti_s2;
wire   [2:0]   awprot_usb3_s0;
wire           awready_hsp2main_m0;
wire   [2:0]   awsize_dvp_s1;
wire   [2:0]   awsize_keti_s2;
wire   [2:0]   awsize_usb3_s0;
wire           awvalid_dvp_s1;
wire           awvalid_keti_s2;
wire           awvalid_usb3_s0;
wire   [5:0]   bid_hsp2main_m0;
wire           bready_dvp_s1;
wire           bready_keti_s2;
wire           bready_usb3_s0;
wire   [1:0]   bresp_hsp2main_m0;
wire           bvalid_hsp2main_m0;
wire           dvpclk;
wire           dvpresetn;
wire   [31:0]  haddr_hsp_gpv_s3;
wire   [2:0]   hburst_hsp_gpv_s3;
wire   [3:0]   hprot_hsp_gpv_s3;
wire   [2:0]   hsize_hsp_gpv_s3;
wire           hsp_gpvclk;
wire           hsp_gpvresetn;
wire   [1:0]   htrans_hsp_gpv_s3;
wire   [31:0]  hwdata_hsp_gpv_s3;
wire           hwrite_hsp_gpv_s3;
wire           keticlk;
wire           ketiresetn;
wire           mainclk;
wire           mainclk_r;
wire           mainresetn;
wire           mainresetn_r;
wire   [31:0]  rdata_hsp2main_m0;
wire   [5:0]   rid_hsp2main_m0;
wire           rlast_hsp2main_m0;
wire           rready_dvp_s1;
wire           rready_keti_s2;
wire           rready_usb3_s0;
wire   [1:0]   rresp_hsp2main_m0;
wire           rvalid_hsp2main_m0;
wire           usb3clk;
wire           usb3resetn;
wire   [127:0] wdata_dvp_s1;
wire   [127:0] wdata_keti_s2;
wire   [127:0] wdata_usb3_s0;
wire           wlast_dvp_s1;
wire           wlast_keti_s2;
wire           wlast_usb3_s0;
wire           wready_hsp2main_m0;
wire   [15:0]  wstrb_dvp_s1;
wire   [15:0]  wstrb_keti_s2;
wire   [15:0]  wstrb_usb3_s0;
wire           wvalid_dvp_s1;
wire           wvalid_keti_s2;
wire           wvalid_usb3_s0;



//-----------------------------------------------------------------------------
// Sub-Modules Instantiation
//-----------------------------------------------------------------------------

nic400_cd_dvp_hsp_bus_r0p00     u_cd_dvp (
  .dvpclk               (dvpclk),    // dvp_s1
  .dvpresetn            (dvpresetn),    // dvp_s1
  .awid_dvp_s1          (awid_dvp_s1),    // dvp_s1
  .awaddr_dvp_s1        (awaddr_dvp_s1),    // dvp_s1
  .awlen_dvp_s1         (awlen_dvp_s1),    // dvp_s1
  .awsize_dvp_s1        (awsize_dvp_s1),    // dvp_s1
  .awburst_dvp_s1       (awburst_dvp_s1),    // dvp_s1
  .awlock_dvp_s1        (awlock_dvp_s1),    // dvp_s1
  .awcache_dvp_s1       (awcache_dvp_s1),    // dvp_s1
  .awprot_dvp_s1        (awprot_dvp_s1),    // dvp_s1
  .awvalid_dvp_s1       (awvalid_dvp_s1),    // dvp_s1
  .awready_dvp_s1       (awready_dvp_s1),    // dvp_s1
  .wdata_dvp_s1         (wdata_dvp_s1),    // dvp_s1
  .wstrb_dvp_s1         (wstrb_dvp_s1),    // dvp_s1
  .wlast_dvp_s1         (wlast_dvp_s1),    // dvp_s1
  .wvalid_dvp_s1        (wvalid_dvp_s1),    // dvp_s1
  .wready_dvp_s1        (wready_dvp_s1),    // dvp_s1
  .bid_dvp_s1           (bid_dvp_s1),    // dvp_s1
  .bresp_dvp_s1         (bresp_dvp_s1),    // dvp_s1
  .bvalid_dvp_s1        (bvalid_dvp_s1),    // dvp_s1
  .bready_dvp_s1        (bready_dvp_s1),    // dvp_s1
  .arid_dvp_s1          (arid_dvp_s1),    // dvp_s1
  .araddr_dvp_s1        (araddr_dvp_s1),    // dvp_s1
  .arlen_dvp_s1         (arlen_dvp_s1),    // dvp_s1
  .arsize_dvp_s1        (arsize_dvp_s1),    // dvp_s1
  .arburst_dvp_s1       (arburst_dvp_s1),    // dvp_s1
  .arlock_dvp_s1        (arlock_dvp_s1),    // dvp_s1
  .arcache_dvp_s1       (arcache_dvp_s1),    // dvp_s1
  .arprot_dvp_s1        (arprot_dvp_s1),    // dvp_s1
  .arvalid_dvp_s1       (arvalid_dvp_s1),    // dvp_s1
  .arready_dvp_s1       (arready_dvp_s1),    // dvp_s1
  .rid_dvp_s1           (rid_dvp_s1),    // dvp_s1
  .rdata_dvp_s1         (rdata_dvp_s1),    // dvp_s1
  .rresp_dvp_s1         (rresp_dvp_s1),    // dvp_s1
  .rlast_dvp_s1         (rlast_dvp_s1),    // dvp_s1
  .rvalid_dvp_s1        (rvalid_dvp_s1),    // dvp_s1
  .rready_dvp_s1        (rready_dvp_s1),    // dvp_s1
  .pack_dvp_s1_ib_apb_int (pack_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .preq_dvp_s1_ib_apb_int (preq_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .pfwdpayld_dvp_s1_ib_apb_int (pfwdpayld_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .prevpayld_dvp_s1_ib_apb_int (prevpayld_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .aw_data_dvp_s1_ib_int (aw_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .aw_wpntr_gry_dvp_s1_ib_int (aw_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .aw_rpntr_bin_dvp_s1_ib_int (aw_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .aw_rpntr_gry_dvp_s1_ib_int (aw_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_data_dvp_s1_ib_int (ar_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_wpntr_gry_dvp_s1_ib_int (ar_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_rpntr_bin_dvp_s1_ib_int (ar_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_rpntr_gry_dvp_s1_ib_int (ar_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_data_dvp_s1_ib_int (w_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_wpntr_gry_dvp_s1_ib_int (w_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_rpntr_bin_dvp_s1_ib_int (w_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_rpntr_gry_dvp_s1_ib_int (w_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_data_dvp_s1_ib_int (r_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_wpntr_gry_dvp_s1_ib_int (r_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_rpntr_bin_dvp_s1_ib_int (r_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_rpntr_gry_dvp_s1_ib_int (r_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_data_dvp_s1_ib_int (b_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_wpntr_gry_dvp_s1_ib_int (b_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_rpntr_bin_dvp_s1_ib_int (b_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_rpntr_gry_dvp_s1_ib_int (b_rpntr_gry_dvp_s1_ib_int)    // dvp_s1_ib_int
);


nic400_cd_hsp_gpv_hsp_bus_r0p00     u_cd_hsp_gpv (
  .hsp_gpvclk           (hsp_gpvclk),    // hsp_gpv_s3
  .hsp_gpvresetn        (hsp_gpvresetn),    // hsp_gpv_s3
  .haddr_hsp_gpv_s3     (haddr_hsp_gpv_s3),    // hsp_gpv_s3
  .hburst_hsp_gpv_s3    (hburst_hsp_gpv_s3),    // hsp_gpv_s3
  .hprot_hsp_gpv_s3     (hprot_hsp_gpv_s3),    // hsp_gpv_s3
  .hsize_hsp_gpv_s3     (hsize_hsp_gpv_s3),    // hsp_gpv_s3
  .htrans_hsp_gpv_s3    (htrans_hsp_gpv_s3),    // hsp_gpv_s3
  .hwdata_hsp_gpv_s3    (hwdata_hsp_gpv_s3),    // hsp_gpv_s3
  .hwrite_hsp_gpv_s3    (hwrite_hsp_gpv_s3),    // hsp_gpv_s3
  .hrdata_hsp_gpv_s3    (hrdata_hsp_gpv_s3),    // hsp_gpv_s3
  .hresp_hsp_gpv_s3     (hresp_hsp_gpv_s3),    // hsp_gpv_s3
  .hready_hsp_gpv_s3    (hready_hsp_gpv_s3),    // hsp_gpv_s3
  .pack_hsp_gpv_s3_ib_apb_int (pack_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .preq_hsp_gpv_s3_ib_apb_int (preq_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .pfwdpayld_hsp_gpv_s3_ib_apb_int (pfwdpayld_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .prevpayld_hsp_gpv_s3_ib_apb_int (prevpayld_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .a_data_hsp_gpv_s3_ib_int (a_data_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .a_wpntr_gry_hsp_gpv_s3_ib_int (a_wpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .a_rpntr_bin_hsp_gpv_s3_ib_int (a_rpntr_bin_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .a_rpntr_gry_hsp_gpv_s3_ib_int (a_rpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_data_hsp_gpv_s3_ib_int (w_data_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_wpntr_gry_hsp_gpv_s3_ib_int (w_wpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_rpntr_bin_hsp_gpv_s3_ib_int (w_rpntr_bin_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_rpntr_gry_hsp_gpv_s3_ib_int (w_rpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_data_hsp_gpv_s3_ib_int (d_data_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_wpntr_gry_hsp_gpv_s3_ib_int (d_wpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_rpntr_bin_hsp_gpv_s3_ib_int (d_rpntr_bin_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_rpntr_gry_hsp_gpv_s3_ib_int (d_rpntr_gry_hsp_gpv_s3_ib_int)    // hsp_gpv_s3_ib_int
);


nic400_cd_keti_hsp_bus_r0p00     u_cd_keti (
  .keticlk              (keticlk),    // keti_s2
  .ketiresetn           (ketiresetn),    // keti_s2
  .awid_keti_s2         (awid_keti_s2),    // keti_s2
  .awaddr_keti_s2       (awaddr_keti_s2),    // keti_s2
  .awlen_keti_s2        (awlen_keti_s2),    // keti_s2
  .awsize_keti_s2       (awsize_keti_s2),    // keti_s2
  .awburst_keti_s2      (awburst_keti_s2),    // keti_s2
  .awlock_keti_s2       (awlock_keti_s2),    // keti_s2
  .awcache_keti_s2      (awcache_keti_s2),    // keti_s2
  .awprot_keti_s2       (awprot_keti_s2),    // keti_s2
  .awvalid_keti_s2      (awvalid_keti_s2),    // keti_s2
  .awready_keti_s2      (awready_keti_s2),    // keti_s2
  .wdata_keti_s2        (wdata_keti_s2),    // keti_s2
  .wstrb_keti_s2        (wstrb_keti_s2),    // keti_s2
  .wlast_keti_s2        (wlast_keti_s2),    // keti_s2
  .wvalid_keti_s2       (wvalid_keti_s2),    // keti_s2
  .wready_keti_s2       (wready_keti_s2),    // keti_s2
  .bid_keti_s2          (bid_keti_s2),    // keti_s2
  .bresp_keti_s2        (bresp_keti_s2),    // keti_s2
  .bvalid_keti_s2       (bvalid_keti_s2),    // keti_s2
  .bready_keti_s2       (bready_keti_s2),    // keti_s2
  .arid_keti_s2         (arid_keti_s2),    // keti_s2
  .araddr_keti_s2       (araddr_keti_s2),    // keti_s2
  .arlen_keti_s2        (arlen_keti_s2),    // keti_s2
  .arsize_keti_s2       (arsize_keti_s2),    // keti_s2
  .arburst_keti_s2      (arburst_keti_s2),    // keti_s2
  .arlock_keti_s2       (arlock_keti_s2),    // keti_s2
  .arcache_keti_s2      (arcache_keti_s2),    // keti_s2
  .arprot_keti_s2       (arprot_keti_s2),    // keti_s2
  .arvalid_keti_s2      (arvalid_keti_s2),    // keti_s2
  .arready_keti_s2      (arready_keti_s2),    // keti_s2
  .rid_keti_s2          (rid_keti_s2),    // keti_s2
  .rdata_keti_s2        (rdata_keti_s2),    // keti_s2
  .rresp_keti_s2        (rresp_keti_s2),    // keti_s2
  .rlast_keti_s2        (rlast_keti_s2),    // keti_s2
  .rvalid_keti_s2       (rvalid_keti_s2),    // keti_s2
  .rready_keti_s2       (rready_keti_s2),    // keti_s2
  .pack_keti_s2_ib_apb_int (pack_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .preq_keti_s2_ib_apb_int (preq_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .pfwdpayld_keti_s2_ib_apb_int (pfwdpayld_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .prevpayld_keti_s2_ib_apb_int (prevpayld_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .aw_data_keti_s2_ib_int (aw_data_keti_s2_ib_int),    // keti_s2_ib_int
  .aw_wpntr_gry_keti_s2_ib_int (aw_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .aw_rpntr_bin_keti_s2_ib_int (aw_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .aw_rpntr_gry_keti_s2_ib_int (aw_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_data_keti_s2_ib_int (ar_data_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_wpntr_gry_keti_s2_ib_int (ar_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_rpntr_bin_keti_s2_ib_int (ar_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_rpntr_gry_keti_s2_ib_int (ar_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .w_data_keti_s2_ib_int (w_data_keti_s2_ib_int),    // keti_s2_ib_int
  .w_wpntr_gry_keti_s2_ib_int (w_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .w_rpntr_bin_keti_s2_ib_int (w_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .w_rpntr_gry_keti_s2_ib_int (w_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .r_data_keti_s2_ib_int (r_data_keti_s2_ib_int),    // keti_s2_ib_int
  .r_wpntr_gry_keti_s2_ib_int (r_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .r_rpntr_bin_keti_s2_ib_int (r_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .r_rpntr_gry_keti_s2_ib_int (r_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .b_data_keti_s2_ib_int (b_data_keti_s2_ib_int),    // keti_s2_ib_int
  .b_wpntr_gry_keti_s2_ib_int (b_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .b_rpntr_bin_keti_s2_ib_int (b_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .b_rpntr_gry_keti_s2_ib_int (b_rpntr_gry_keti_s2_ib_int)    // keti_s2_ib_int
);


nic400_cd_main_hsp_bus_r0p00     u_cd_main (
  .paddr_dvp_s1_ib_apb  (paddr_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pselx_dvp_s1_ib_apb  (pselx_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .penable_dvp_s1_ib_apb (penable_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pwrite_dvp_s1_ib_apb (pwrite_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .prdata_dvp_s1_ib_apb (prdata_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pwdata_dvp_s1_ib_apb (pwdata_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pready_dvp_s1_ib_apb (pready_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pslverr_dvp_s1_ib_apb (pslverr_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pack_dvp_s1_ib_apb_int (pack_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .preq_dvp_s1_ib_apb_int (preq_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .pfwdpayld_dvp_s1_ib_apb_int (pfwdpayld_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .prevpayld_dvp_s1_ib_apb_int (prevpayld_dvp_s1_ib_apb_int),    // dvp_s1_ib_apb_int
  .aw_data_dvp_s1_ib_int (aw_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .aw_wpntr_gry_dvp_s1_ib_int (aw_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .aw_rpntr_bin_dvp_s1_ib_int (aw_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .aw_rpntr_gry_dvp_s1_ib_int (aw_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_data_dvp_s1_ib_int (ar_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_wpntr_gry_dvp_s1_ib_int (ar_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_rpntr_bin_dvp_s1_ib_int (ar_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .ar_rpntr_gry_dvp_s1_ib_int (ar_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_data_dvp_s1_ib_int (w_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_wpntr_gry_dvp_s1_ib_int (w_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_rpntr_bin_dvp_s1_ib_int (w_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .w_rpntr_gry_dvp_s1_ib_int (w_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_data_dvp_s1_ib_int (r_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_wpntr_gry_dvp_s1_ib_int (r_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_rpntr_bin_dvp_s1_ib_int (r_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .r_rpntr_gry_dvp_s1_ib_int (r_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_data_dvp_s1_ib_int (b_data_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_wpntr_gry_dvp_s1_ib_int (b_wpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_rpntr_bin_dvp_s1_ib_int (b_rpntr_bin_dvp_s1_ib_int),    // dvp_s1_ib_int
  .b_rpntr_gry_dvp_s1_ib_int (b_rpntr_gry_dvp_s1_ib_int),    // dvp_s1_ib_int
  .awid_hsp2main_m0     (awid_hsp2main_m0),    // hsp2main_m0
  .awaddr_hsp2main_m0   (awaddr_hsp2main_m0),    // hsp2main_m0
  .awlen_hsp2main_m0    (awlen_hsp2main_m0),    // hsp2main_m0
  .awsize_hsp2main_m0   (awsize_hsp2main_m0),    // hsp2main_m0
  .awburst_hsp2main_m0  (awburst_hsp2main_m0),    // hsp2main_m0
  .awlock_hsp2main_m0   (awlock_hsp2main_m0),    // hsp2main_m0
  .awcache_hsp2main_m0  (awcache_hsp2main_m0),    // hsp2main_m0
  .awprot_hsp2main_m0   (awprot_hsp2main_m0),    // hsp2main_m0
  .awvalid_hsp2main_m0  (awvalid_hsp2main_m0),    // hsp2main_m0
  .awready_hsp2main_m0  (awready_hsp2main_m0),    // hsp2main_m0
  .wdata_hsp2main_m0    (wdata_hsp2main_m0),    // hsp2main_m0
  .wstrb_hsp2main_m0    (wstrb_hsp2main_m0),    // hsp2main_m0
  .wlast_hsp2main_m0    (wlast_hsp2main_m0),    // hsp2main_m0
  .wvalid_hsp2main_m0   (wvalid_hsp2main_m0),    // hsp2main_m0
  .wready_hsp2main_m0   (wready_hsp2main_m0),    // hsp2main_m0
  .bid_hsp2main_m0      (bid_hsp2main_m0),    // hsp2main_m0
  .bresp_hsp2main_m0    (bresp_hsp2main_m0),    // hsp2main_m0
  .bvalid_hsp2main_m0   (bvalid_hsp2main_m0),    // hsp2main_m0
  .bready_hsp2main_m0   (bready_hsp2main_m0),    // hsp2main_m0
  .arid_hsp2main_m0     (arid_hsp2main_m0),    // hsp2main_m0
  .araddr_hsp2main_m0   (araddr_hsp2main_m0),    // hsp2main_m0
  .arlen_hsp2main_m0    (arlen_hsp2main_m0),    // hsp2main_m0
  .arsize_hsp2main_m0   (arsize_hsp2main_m0),    // hsp2main_m0
  .arburst_hsp2main_m0  (arburst_hsp2main_m0),    // hsp2main_m0
  .arlock_hsp2main_m0   (arlock_hsp2main_m0),    // hsp2main_m0
  .arcache_hsp2main_m0  (arcache_hsp2main_m0),    // hsp2main_m0
  .arprot_hsp2main_m0   (arprot_hsp2main_m0),    // hsp2main_m0
  .arvalid_hsp2main_m0  (arvalid_hsp2main_m0),    // hsp2main_m0
  .arready_hsp2main_m0  (arready_hsp2main_m0),    // hsp2main_m0
  .rid_hsp2main_m0      (rid_hsp2main_m0),    // hsp2main_m0
  .rdata_hsp2main_m0    (rdata_hsp2main_m0),    // hsp2main_m0
  .rresp_hsp2main_m0    (rresp_hsp2main_m0),    // hsp2main_m0
  .rlast_hsp2main_m0    (rlast_hsp2main_m0),    // hsp2main_m0
  .rvalid_hsp2main_m0   (rvalid_hsp2main_m0),    // hsp2main_m0
  .rready_hsp2main_m0   (rready_hsp2main_m0),    // hsp2main_m0
  .paddr_hsp2main_m0_ib_apb (paddr_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pselx_hsp2main_m0_ib_apb (pselx_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .penable_hsp2main_m0_ib_apb (penable_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pwrite_hsp2main_m0_ib_apb (pwrite_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .prdata_hsp2main_m0_ib_apb (prdata_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pwdata_hsp2main_m0_ib_apb (pwdata_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pready_hsp2main_m0_ib_apb (pready_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pslverr_hsp2main_m0_ib_apb (pslverr_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .a_data_hsp_gpv_ib1_int (a_data_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .a_valid_hsp_gpv_ib1_int (a_valid_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .a_ready_hsp_gpv_ib1_int (a_ready_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .w_data_hsp_gpv_ib1_int (w_data_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .w_valid_hsp_gpv_ib1_int (w_valid_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .w_ready_hsp_gpv_ib1_int (w_ready_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .d_data_hsp_gpv_ib1_int (d_data_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .d_valid_hsp_gpv_ib1_int (d_valid_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .d_ready_hsp_gpv_ib1_int (d_ready_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .paddr_hsp_gpv_s3_ib_apb (paddr_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pselx_hsp_gpv_s3_ib_apb (pselx_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .penable_hsp_gpv_s3_ib_apb (penable_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pwrite_hsp_gpv_s3_ib_apb (pwrite_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .prdata_hsp_gpv_s3_ib_apb (prdata_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pwdata_hsp_gpv_s3_ib_apb (pwdata_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pready_hsp_gpv_s3_ib_apb (pready_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pslverr_hsp_gpv_s3_ib_apb (pslverr_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pack_hsp_gpv_s3_ib_apb_int (pack_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .preq_hsp_gpv_s3_ib_apb_int (preq_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .pfwdpayld_hsp_gpv_s3_ib_apb_int (pfwdpayld_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .prevpayld_hsp_gpv_s3_ib_apb_int (prevpayld_hsp_gpv_s3_ib_apb_int),    // hsp_gpv_s3_ib_apb_int
  .a_data_hsp_gpv_s3_ib_int (a_data_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .a_wpntr_gry_hsp_gpv_s3_ib_int (a_wpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .a_rpntr_bin_hsp_gpv_s3_ib_int (a_rpntr_bin_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .a_rpntr_gry_hsp_gpv_s3_ib_int (a_rpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_data_hsp_gpv_s3_ib_int (w_data_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_wpntr_gry_hsp_gpv_s3_ib_int (w_wpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_rpntr_bin_hsp_gpv_s3_ib_int (w_rpntr_bin_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .w_rpntr_gry_hsp_gpv_s3_ib_int (w_rpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_data_hsp_gpv_s3_ib_int (d_data_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_wpntr_gry_hsp_gpv_s3_ib_int (d_wpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_rpntr_bin_hsp_gpv_s3_ib_int (d_rpntr_bin_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .d_rpntr_gry_hsp_gpv_s3_ib_int (d_rpntr_gry_hsp_gpv_s3_ib_int),    // hsp_gpv_s3_ib_int
  .paddr_keti_s2_ib_apb (paddr_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pselx_keti_s2_ib_apb (pselx_keti_s2_ib_apb),    // keti_s2_ib_apb
  .penable_keti_s2_ib_apb (penable_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pwrite_keti_s2_ib_apb (pwrite_keti_s2_ib_apb),    // keti_s2_ib_apb
  .prdata_keti_s2_ib_apb (prdata_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pwdata_keti_s2_ib_apb (pwdata_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pready_keti_s2_ib_apb (pready_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pslverr_keti_s2_ib_apb (pslverr_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pack_keti_s2_ib_apb_int (pack_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .preq_keti_s2_ib_apb_int (preq_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .pfwdpayld_keti_s2_ib_apb_int (pfwdpayld_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .prevpayld_keti_s2_ib_apb_int (prevpayld_keti_s2_ib_apb_int),    // keti_s2_ib_apb_int
  .aw_data_keti_s2_ib_int (aw_data_keti_s2_ib_int),    // keti_s2_ib_int
  .aw_wpntr_gry_keti_s2_ib_int (aw_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .aw_rpntr_bin_keti_s2_ib_int (aw_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .aw_rpntr_gry_keti_s2_ib_int (aw_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_data_keti_s2_ib_int (ar_data_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_wpntr_gry_keti_s2_ib_int (ar_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_rpntr_bin_keti_s2_ib_int (ar_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .ar_rpntr_gry_keti_s2_ib_int (ar_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .w_data_keti_s2_ib_int (w_data_keti_s2_ib_int),    // keti_s2_ib_int
  .w_wpntr_gry_keti_s2_ib_int (w_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .w_rpntr_bin_keti_s2_ib_int (w_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .w_rpntr_gry_keti_s2_ib_int (w_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .r_data_keti_s2_ib_int (r_data_keti_s2_ib_int),    // keti_s2_ib_int
  .r_wpntr_gry_keti_s2_ib_int (r_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .r_rpntr_bin_keti_s2_ib_int (r_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .r_rpntr_gry_keti_s2_ib_int (r_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .b_data_keti_s2_ib_int (b_data_keti_s2_ib_int),    // keti_s2_ib_int
  .b_wpntr_gry_keti_s2_ib_int (b_wpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .b_rpntr_bin_keti_s2_ib_int (b_rpntr_bin_keti_s2_ib_int),    // keti_s2_ib_int
  .b_rpntr_gry_keti_s2_ib_int (b_rpntr_gry_keti_s2_ib_int),    // keti_s2_ib_int
  .mainclk              (mainclk),    // usb3_s0_ib_apb
  .mainresetn           (mainresetn),    // usb3_s0_ib_apb
  .paddr_usb3_s0_ib_apb (paddr_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pselx_usb3_s0_ib_apb (pselx_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .penable_usb3_s0_ib_apb (penable_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pwrite_usb3_s0_ib_apb (pwrite_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .prdata_usb3_s0_ib_apb (prdata_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pwdata_usb3_s0_ib_apb (pwdata_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pready_usb3_s0_ib_apb (pready_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pslverr_usb3_s0_ib_apb (pslverr_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pack_usb3_s0_ib_apb_int (pack_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .preq_usb3_s0_ib_apb_int (preq_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .pfwdpayld_usb3_s0_ib_apb_int (pfwdpayld_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .prevpayld_usb3_s0_ib_apb_int (prevpayld_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .aw_data_usb3_s0_ib_int (aw_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .aw_wpntr_gry_usb3_s0_ib_int (aw_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .aw_rpntr_bin_usb3_s0_ib_int (aw_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .aw_rpntr_gry_usb3_s0_ib_int (aw_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_data_usb3_s0_ib_int (ar_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_wpntr_gry_usb3_s0_ib_int (ar_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_rpntr_bin_usb3_s0_ib_int (ar_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_rpntr_gry_usb3_s0_ib_int (ar_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_data_usb3_s0_ib_int (w_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_wpntr_gry_usb3_s0_ib_int (w_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_rpntr_bin_usb3_s0_ib_int (w_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_rpntr_gry_usb3_s0_ib_int (w_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_data_usb3_s0_ib_int (r_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_wpntr_gry_usb3_s0_ib_int (r_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_rpntr_bin_usb3_s0_ib_int (r_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_rpntr_gry_usb3_s0_ib_int (r_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_data_usb3_s0_ib_int (b_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_wpntr_gry_usb3_s0_ib_int (b_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_rpntr_bin_usb3_s0_ib_int (b_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_rpntr_gry_usb3_s0_ib_int (b_rpntr_gry_usb3_s0_ib_int)    // usb3_s0_ib_int
);


nic400_cd_usb3_hsp_bus_r0p00     u_cd_usb3 (
  .usb3clk              (usb3clk),    // usb3_s0
  .usb3resetn           (usb3resetn),    // usb3_s0
  .awid_usb3_s0         (awid_usb3_s0),    // usb3_s0
  .awaddr_usb3_s0       (awaddr_usb3_s0),    // usb3_s0
  .awlen_usb3_s0        (awlen_usb3_s0),    // usb3_s0
  .awsize_usb3_s0       (awsize_usb3_s0),    // usb3_s0
  .awburst_usb3_s0      (awburst_usb3_s0),    // usb3_s0
  .awlock_usb3_s0       (awlock_usb3_s0),    // usb3_s0
  .awcache_usb3_s0      (awcache_usb3_s0),    // usb3_s0
  .awprot_usb3_s0       (awprot_usb3_s0),    // usb3_s0
  .awvalid_usb3_s0      (awvalid_usb3_s0),    // usb3_s0
  .awready_usb3_s0      (awready_usb3_s0),    // usb3_s0
  .wdata_usb3_s0        (wdata_usb3_s0),    // usb3_s0
  .wstrb_usb3_s0        (wstrb_usb3_s0),    // usb3_s0
  .wlast_usb3_s0        (wlast_usb3_s0),    // usb3_s0
  .wvalid_usb3_s0       (wvalid_usb3_s0),    // usb3_s0
  .wready_usb3_s0       (wready_usb3_s0),    // usb3_s0
  .bid_usb3_s0          (bid_usb3_s0),    // usb3_s0
  .bresp_usb3_s0        (bresp_usb3_s0),    // usb3_s0
  .bvalid_usb3_s0       (bvalid_usb3_s0),    // usb3_s0
  .bready_usb3_s0       (bready_usb3_s0),    // usb3_s0
  .arid_usb3_s0         (arid_usb3_s0),    // usb3_s0
  .araddr_usb3_s0       (araddr_usb3_s0),    // usb3_s0
  .arlen_usb3_s0        (arlen_usb3_s0),    // usb3_s0
  .arsize_usb3_s0       (arsize_usb3_s0),    // usb3_s0
  .arburst_usb3_s0      (arburst_usb3_s0),    // usb3_s0
  .arlock_usb3_s0       (arlock_usb3_s0),    // usb3_s0
  .arcache_usb3_s0      (arcache_usb3_s0),    // usb3_s0
  .arprot_usb3_s0       (arprot_usb3_s0),    // usb3_s0
  .arvalid_usb3_s0      (arvalid_usb3_s0),    // usb3_s0
  .arready_usb3_s0      (arready_usb3_s0),    // usb3_s0
  .rid_usb3_s0          (rid_usb3_s0),    // usb3_s0
  .rdata_usb3_s0        (rdata_usb3_s0),    // usb3_s0
  .rresp_usb3_s0        (rresp_usb3_s0),    // usb3_s0
  .rlast_usb3_s0        (rlast_usb3_s0),    // usb3_s0
  .rvalid_usb3_s0       (rvalid_usb3_s0),    // usb3_s0
  .rready_usb3_s0       (rready_usb3_s0),    // usb3_s0
  .pack_usb3_s0_ib_apb_int (pack_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .preq_usb3_s0_ib_apb_int (preq_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .pfwdpayld_usb3_s0_ib_apb_int (pfwdpayld_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .prevpayld_usb3_s0_ib_apb_int (prevpayld_usb3_s0_ib_apb_int),    // usb3_s0_ib_apb_int
  .aw_data_usb3_s0_ib_int (aw_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .aw_wpntr_gry_usb3_s0_ib_int (aw_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .aw_rpntr_bin_usb3_s0_ib_int (aw_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .aw_rpntr_gry_usb3_s0_ib_int (aw_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_data_usb3_s0_ib_int (ar_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_wpntr_gry_usb3_s0_ib_int (ar_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_rpntr_bin_usb3_s0_ib_int (ar_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .ar_rpntr_gry_usb3_s0_ib_int (ar_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_data_usb3_s0_ib_int (w_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_wpntr_gry_usb3_s0_ib_int (w_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_rpntr_bin_usb3_s0_ib_int (w_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .w_rpntr_gry_usb3_s0_ib_int (w_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_data_usb3_s0_ib_int (r_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_wpntr_gry_usb3_s0_ib_int (r_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_rpntr_bin_usb3_s0_ib_int (r_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .r_rpntr_gry_usb3_s0_ib_int (r_rpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_data_usb3_s0_ib_int (b_data_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_wpntr_gry_usb3_s0_ib_int (b_wpntr_gry_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_rpntr_bin_usb3_s0_ib_int (b_rpntr_bin_usb3_s0_ib_int),    // usb3_s0_ib_int
  .b_rpntr_gry_usb3_s0_ib_int (b_rpntr_gry_usb3_s0_ib_int)    // usb3_s0_ib_int
);


nic400_cd_main_r_hsp_bus_r0p00     u_r_cd_main (
  .paddr_dvp_s1_ib_apb  (paddr_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pselx_dvp_s1_ib_apb  (pselx_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .penable_dvp_s1_ib_apb (penable_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pwrite_dvp_s1_ib_apb (pwrite_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .prdata_dvp_s1_ib_apb (prdata_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pwdata_dvp_s1_ib_apb (pwdata_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pready_dvp_s1_ib_apb (pready_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .pslverr_dvp_s1_ib_apb (pslverr_dvp_s1_ib_apb),    // dvp_s1_ib_apb
  .paddr_hsp2main_m0_ib_apb (paddr_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pselx_hsp2main_m0_ib_apb (pselx_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .penable_hsp2main_m0_ib_apb (penable_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pwrite_hsp2main_m0_ib_apb (pwrite_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .prdata_hsp2main_m0_ib_apb (prdata_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pwdata_hsp2main_m0_ib_apb (pwdata_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pready_hsp2main_m0_ib_apb (pready_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .pslverr_hsp2main_m0_ib_apb (pslverr_hsp2main_m0_ib_apb),    // hsp2main_m0_ib_apb
  .a_data_hsp_gpv_ib1_int (a_data_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .a_valid_hsp_gpv_ib1_int (a_valid_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .a_ready_hsp_gpv_ib1_int (a_ready_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .w_data_hsp_gpv_ib1_int (w_data_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .w_valid_hsp_gpv_ib1_int (w_valid_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .w_ready_hsp_gpv_ib1_int (w_ready_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .d_data_hsp_gpv_ib1_int (d_data_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .d_valid_hsp_gpv_ib1_int (d_valid_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .d_ready_hsp_gpv_ib1_int (d_ready_hsp_gpv_ib1_int),    // hsp_gpv_ib1_int
  .paddr_hsp_gpv_s3_ib_apb (paddr_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pselx_hsp_gpv_s3_ib_apb (pselx_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .penable_hsp_gpv_s3_ib_apb (penable_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pwrite_hsp_gpv_s3_ib_apb (pwrite_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .prdata_hsp_gpv_s3_ib_apb (prdata_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pwdata_hsp_gpv_s3_ib_apb (pwdata_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pready_hsp_gpv_s3_ib_apb (pready_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .pslverr_hsp_gpv_s3_ib_apb (pslverr_hsp_gpv_s3_ib_apb),    // hsp_gpv_s3_ib_apb
  .paddr_keti_s2_ib_apb (paddr_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pselx_keti_s2_ib_apb (pselx_keti_s2_ib_apb),    // keti_s2_ib_apb
  .penable_keti_s2_ib_apb (penable_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pwrite_keti_s2_ib_apb (pwrite_keti_s2_ib_apb),    // keti_s2_ib_apb
  .prdata_keti_s2_ib_apb (prdata_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pwdata_keti_s2_ib_apb (pwdata_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pready_keti_s2_ib_apb (pready_keti_s2_ib_apb),    // keti_s2_ib_apb
  .pslverr_keti_s2_ib_apb (pslverr_keti_s2_ib_apb),    // keti_s2_ib_apb
  .rsb_data_main_ml_m   (rsb_data_main_ml_m),    // main_ml_m
  .rsb_wptr_main_ml_m   (rsb_wptr_main_ml_m),    // main_ml_m
  .rsb_rptr_main_ml_m   (rsb_rptr_main_ml_m),    // main_ml_m
  .rsb_bin_rptr_main_ml_m (rsb_bin_rptr_main_ml_m),    // main_ml_m
  .rsb_data_main_ml_s   (rsb_data_main_ml_s),    // main_ml_s
  .rsb_wptr_main_ml_s   (rsb_wptr_main_ml_s),    // main_ml_s
  .rsb_rptr_main_ml_s   (rsb_rptr_main_ml_s),    // main_ml_s
  .rsb_bin_rptr_main_ml_s (rsb_bin_rptr_main_ml_s),    // main_ml_s
  .rsb_data_main_sl_m   (rsb_data_main_sl_m),    // main_sl_m
  .rsb_wptr_main_sl_m   (rsb_wptr_main_sl_m),    // main_sl_m
  .rsb_rptr_main_sl_m   (rsb_rptr_main_sl_m),    // main_sl_m
  .rsb_bin_rptr_main_sl_m (rsb_bin_rptr_main_sl_m),    // main_sl_m
  .rsb_data_main_sl_s   (rsb_data_main_sl_s),    // main_sl_s
  .rsb_wptr_main_sl_s   (rsb_wptr_main_sl_s),    // main_sl_s
  .rsb_rptr_main_sl_s   (rsb_rptr_main_sl_s),    // main_sl_s
  .rsb_bin_rptr_main_sl_s (rsb_bin_rptr_main_sl_s),    // main_sl_s
  .mainclk_r            (mainclk_r),    // usb3_s0_ib_apb
  .mainresetn_r         (mainresetn_r),    // usb3_s0_ib_apb
  .paddr_usb3_s0_ib_apb (paddr_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pselx_usb3_s0_ib_apb (pselx_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .penable_usb3_s0_ib_apb (penable_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pwrite_usb3_s0_ib_apb (pwrite_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .prdata_usb3_s0_ib_apb (prdata_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pwdata_usb3_s0_ib_apb (pwdata_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pready_usb3_s0_ib_apb (pready_usb3_s0_ib_apb),    // usb3_s0_ib_apb
  .pslverr_usb3_s0_ib_apb (pslverr_usb3_s0_ib_apb)    // usb3_s0_ib_apb
);


nic400_rsb_connections_hsp_bus_r0p00     u_rsb_conns (
  .rsb_data_main_master_m (rsb_data_main_ml_s),    // main_master_m
  .rsb_wptr_main_master_m (rsb_wptr_main_ml_s),    // main_master_m
  .rsb_rptr_main_master_m (rsb_rptr_main_ml_s),    // main_master_m
  .rsb_b_rptr_main_master_m (rsb_bin_rptr_main_ml_s),    // main_master_m
  .rsb_data_main_master_s (rsb_data_main_ml_m),    // main_master_s
  .rsb_wptr_main_master_s (rsb_wptr_main_ml_m),    // main_master_s
  .rsb_rptr_main_master_s (rsb_rptr_main_ml_m),    // main_master_s
  .rsb_b_rptr_main_master_s (rsb_bin_rptr_main_ml_m),    // main_master_s
  .rsb_data_main_slave_m (rsb_data_main_sl_s),    // main_slave_m
  .rsb_wptr_main_slave_m (rsb_wptr_main_sl_s),    // main_slave_m
  .rsb_rptr_main_slave_m (rsb_rptr_main_sl_s),    // main_slave_m
  .rsb_b_rptr_main_slave_m (rsb_bin_rptr_main_sl_s),    // main_slave_m
  .rsb_data_main_slave_s (rsb_data_main_sl_m),    // main_slave_s
  .rsb_wptr_main_slave_s (rsb_wptr_main_sl_m),    // main_slave_s
  .rsb_rptr_main_slave_s (rsb_rptr_main_sl_m),    // main_slave_s
  .rsb_b_rptr_main_slave_s (rsb_bin_rptr_main_sl_m)    // main_slave_s
);



endmodule
