//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// The confidential and proprietary information contained in this file may     
// only be used by a person authorised under and to the extent permitted       
// by a subsisting licensing agreement from ARM Limited.                       
//                                                                             
//            (C) COPYRIGHT 2005-2015 ARM Limited.
//                ALL RIGHTS RESERVED                                          
//                                                                             
// This entire notice must be reproduced on all copies of this file            
// and copies of this file may only be made by a person if such person is      
// permitted to do so under the terms of a subsisting license agreement        
// from ARM Limited.                                                           
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Top-Level Verilog file is auto-generated by AMBA Designer ADr3p5-01eac0-build-0005

//                                                                             
// Stitcher: generic_stitcher_core v3.1, built on Dec  1 2015
//                                                                             
// Filename: nic400_wn7_cpu_r0p18.v
// Created : Mon Apr 23 13:53:56 2018                            
//                                                                             
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Generated with Validator version1.0


//-----------------------------------------------------------------------------
// Module Declaration nic400_wn7_cpu_r0p18
//-----------------------------------------------------------------------------

module bus_cpu (
  
// Instance: u_cd_cad7, Port: cad7_s0

  awid_s0,
  awaddr_s0,
  awlen_s0,
  awsize_s0,
  awburst_s0,
  awlock_s0,
  awcache_s0,
  awprot_s0,
  awvalid_s0,
  awready_s0,
  wdata_s0,
  wstrb_s0,
  wlast_s0,
  wvalid_s0,
  wready_s0,
  bid_s0,
  bresp_s0,
  bvalid_s0,
  bready_s0,
  arid_s0,
  araddr_s0,
  arlen_s0,
  arsize_s0,
  arburst_s0,
  arlock_s0,
  arcache_s0,
  arprot_s0,
  arvalid_s0,
  arready_s0,
  rid_s0,
  rdata_s0,
  rresp_s0,
  rlast_s0,
  rvalid_s0,
  rready_s0,
  awuser_s0,
  aruser_s0,

  awid_s1,
  awaddr_s1,
  awlen_s1,
  awsize_s1,
  awburst_s1,
  awlock_s1,
  awcache_s1,
  awprot_s1,
  awvalid_s1,
  awready_s1,
  wdata_s1,
  wstrb_s1,
  wlast_s1,
  wvalid_s1,
  wready_s1,
  bid_s1,
  bresp_s1,
  bvalid_s1,
  bready_s1,
  arid_s1,
  araddr_s1,
  arlen_s1,
  arsize_s1,
  arburst_s1,
  arlock_s1,
  arcache_s1,
  arprot_s1,
  arvalid_s1,
  arready_s1,
  rid_s1,
  rdata_s1,
  rresp_s1,
  rlast_s1,
  rvalid_s1,
  rready_s1,
  awuser_s1,
  aruser_s1,
  


// Instance: u_cd_cpu2main, Port: cpu2main_m4

  awid_cpu2main_m4,
  awaddr_cpu2main_m4,
  awlen_cpu2main_m4,
  awsize_cpu2main_m4,
  awburst_cpu2main_m4,
  awlock_cpu2main_m4,
  awcache_cpu2main_m4,
  awprot_cpu2main_m4,
  awvalid_cpu2main_m4,
  awready_cpu2main_m4,
  wdata_cpu2main_m4,
  wstrb_cpu2main_m4,
  wlast_cpu2main_m4,
  wvalid_cpu2main_m4,
  wready_cpu2main_m4,
  bid_cpu2main_m4,
  bresp_cpu2main_m4,
  bvalid_cpu2main_m4,
  bready_cpu2main_m4,
  arid_cpu2main_m4,
  araddr_cpu2main_m4,
  arlen_cpu2main_m4,
  arsize_cpu2main_m4,
  arburst_cpu2main_m4,
  arlock_cpu2main_m4,
  arcache_cpu2main_m4,
  arprot_cpu2main_m4,
  arvalid_cpu2main_m4,
  arready_cpu2main_m4,
  rid_cpu2main_m4,
  rdata_cpu2main_m4,
  rresp_cpu2main_m4,
  rlast_cpu2main_m4,
  rvalid_cpu2main_m4,
  rready_cpu2main_m4,
  awuser_cpu2main_m4,
  aruser_cpu2main_m4,
  
// Instance: u_cd_cpu2peri, Port: cpu2peri_m3

  awid_cpu2peri_m3,
  awaddr_cpu2peri_m3,
  awlen_cpu2peri_m3,
  awsize_cpu2peri_m3,
  awburst_cpu2peri_m3,
  awlock_cpu2peri_m3,
  awcache_cpu2peri_m3,
  awprot_cpu2peri_m3,
  awvalid_cpu2peri_m3,
  awready_cpu2peri_m3,
  wdata_cpu2peri_m3,
  wstrb_cpu2peri_m3,
  wlast_cpu2peri_m3,
  wvalid_cpu2peri_m3,
  wready_cpu2peri_m3,
  bid_cpu2peri_m3,
  bresp_cpu2peri_m3,
  bvalid_cpu2peri_m3,
  bready_cpu2peri_m3,
  arid_cpu2peri_m3,
  araddr_cpu2peri_m3,
  arlen_cpu2peri_m3,
  arsize_cpu2peri_m3,
  arburst_cpu2peri_m3,
  arlock_cpu2peri_m3,
  arcache_cpu2peri_m3,
  arprot_cpu2peri_m3,
  arvalid_cpu2peri_m3,
  arready_cpu2peri_m3,
  rid_cpu2peri_m3,
  rdata_cpu2peri_m3,
  rresp_cpu2peri_m3,
  rlast_cpu2peri_m3,
  rvalid_cpu2peri_m3,
  rready_cpu2peri_m3,
  

// Instance: u_cd_hsp2cpu, Port: hsp2cpu_s5

  awid_hsp2cpu_s5,
  awaddr_hsp2cpu_s5,
  awlen_hsp2cpu_s5,
  awsize_hsp2cpu_s5,
  awburst_hsp2cpu_s5,
  awlock_hsp2cpu_s5,
  awcache_hsp2cpu_s5,
  awprot_hsp2cpu_s5,
  awvalid_hsp2cpu_s5,
  awready_hsp2cpu_s5,
  wdata_hsp2cpu_s5,
  wstrb_hsp2cpu_s5,
  wlast_hsp2cpu_s5,
  wvalid_hsp2cpu_s5,
  wready_hsp2cpu_s5,
  bid_hsp2cpu_s5,
  bresp_hsp2cpu_s5,
  bvalid_hsp2cpu_s5,
  bready_hsp2cpu_s5,
  arid_hsp2cpu_s5,
  araddr_hsp2cpu_s5,
  arlen_hsp2cpu_s5,
  arsize_hsp2cpu_s5,
  arburst_hsp2cpu_s5,
  arlock_hsp2cpu_s5,
  arcache_hsp2cpu_s5,
  arprot_hsp2cpu_s5,
  arvalid_hsp2cpu_s5,
  arready_hsp2cpu_s5,
  rid_hsp2cpu_s5,
  rdata_hsp2cpu_s5,
  rresp_hsp2cpu_s5,
  rlast_hsp2cpu_s5,
  rvalid_hsp2cpu_s5,
  rready_hsp2cpu_s5,
  
// Instance: u_cd_iram, Port: iram_m1

  haddr_iram_m1,
  hburst_iram_m1,
  hprot_iram_m1,
  hsize_iram_m1,
  htrans_iram_m1,
  hwdata_iram_m1,
  hwrite_iram_m1,
  hrdata_iram_m1,
  hreadyout_iram_m1,
  hresp_iram_m1,
  hselx_iram_m1,
  hready_iram_m1,
  
// Instance: u_cd_irom, Port: irom_m0

  haddr_irom_m0,
  hburst_irom_m0,
  hprot_irom_m0,
  hsize_irom_m0,
  htrans_irom_m0,
  hwdata_irom_m0,
  hwrite_irom_m0,
  hrdata_irom_m0,
  hreadyout_irom_m0,
  hresp_irom_m0,
  hselx_irom_m0,
  hready_irom_m0,
  
//  Non-bus signals

  cad7clk,
  cad7resetn,
  cpu2mainclk,
  cpu2mainresetn,
  cpu2periclk,
  cpu2periresetn,
  hsp2cpuclk,
  hsp2cpuresetn,
  iramclk,
  iramresetn,
  iromclk,
  iromresetn,
  mainclk,
  mainclk_r,
  mainresetn,
  mainresetn_r,
);



//-----------------------------------------------------------------------------
// Port Declarations
//-----------------------------------------------------------------------------
// Instance: u_cd_cad7, Port: cad7_s0
input  [5:0]  awid_s0;
input  [32:0] awaddr_s0;
input  [7:0]  awlen_s0;
input  [2:0]  awsize_s0;
input  [1:0]  awburst_s0;
input  [1:0]  awlock_s0;
input  [3:0]  awcache_s0;
input  [2:0]  awprot_s0;
input         awvalid_s0;
output        awready_s0;
input  [127:0] wdata_s0;
input  [15:0] wstrb_s0;
input         wlast_s0;
input         wvalid_s0;
output        wready_s0;
output [5:0]  bid_s0;
output [1:0]  bresp_s0;
output        bvalid_s0;
input         bready_s0;
input  [5:0]  arid_s0;
input  [32:0] araddr_s0;
input  [7:0]  arlen_s0;
input  [2:0]  arsize_s0;
input  [1:0]  arburst_s0;
input         arlock_s0;
input  [3:0]  arcache_s0;
input  [2:0]  arprot_s0;
input         arvalid_s0;
output        arready_s0;
output [5:0]  rid_s0;
output [127:0] rdata_s0;
output [1:0]  rresp_s0;
output        rlast_s0;
output        rvalid_s0;
input         rready_s0;
input  [2:0]  awuser_s0;
input  [2:0]  aruser_s0;

input  [5:0]  awid_s1;
input  [32:0] awaddr_s1;
input  [7:0]  awlen_s1;
input  [2:0]  awsize_s1;
input  [1:0]  awburst_s1;
input         awlock_s1;
input  [3:0]  awcache_s1;
input  [2:0]  awprot_s1;
input         awvalid_s1;
output        awready_s1;
input  [127:0] wdata_s1;
input  [15:0] wstrb_s1;
input         wlast_s1;
input         wvalid_s1;
output        wready_s1;
output [5:0]  bid_s1;
output [1:0]  bresp_s1;
output        bvalid_s1;
input         bready_s1;
input  [5:0]  arid_s1;
input  [32:0] araddr_s1;
input  [7:0]  arlen_s1;
input  [2:0]  arsize_s1;
input  [1:0]  arburst_s1;
input         arlock_s1;
input  [3:0]  arcache_s1;
input  [2:0]  arprot_s1;
input         arvalid_s1;
output        arready_s1;
output [5:0]  rid_s1;
output [127:0] rdata_s1;
output [1:0]  rresp_s1;
output        rlast_s1;
output        rvalid_s1;
input         rready_s1;
input  [2:0]  awuser_s1;
input  [2:0]  aruser_s1;


// Instance: u_cd_cpu2main, Port: cpu2main_m4

output [10:0] awid_cpu2main_m4;
output [32:0] awaddr_cpu2main_m4;
output [7:0]  awlen_cpu2main_m4;
output [2:0]  awsize_cpu2main_m4;
output [1:0]  awburst_cpu2main_m4;
output        awlock_cpu2main_m4;
output [3:0]  awcache_cpu2main_m4;
output [2:0]  awprot_cpu2main_m4;
output        awvalid_cpu2main_m4;
input         awready_cpu2main_m4;
output [127:0] wdata_cpu2main_m4;
output [15:0] wstrb_cpu2main_m4;
output        wlast_cpu2main_m4;
output        wvalid_cpu2main_m4;
input         wready_cpu2main_m4;
input  [10:0] bid_cpu2main_m4;
input  [1:0]  bresp_cpu2main_m4;
input         bvalid_cpu2main_m4;
output        bready_cpu2main_m4;
output [10:0] arid_cpu2main_m4;
output [32:0] araddr_cpu2main_m4;
output [7:0]  arlen_cpu2main_m4;
output [2:0]  arsize_cpu2main_m4;
output [1:0]  arburst_cpu2main_m4;
output        arlock_cpu2main_m4;
output [3:0]  arcache_cpu2main_m4;
output [2:0]  arprot_cpu2main_m4;
output        arvalid_cpu2main_m4;
input         arready_cpu2main_m4;
input  [10:0] rid_cpu2main_m4;
input  [127:0] rdata_cpu2main_m4;
input  [1:0]  rresp_cpu2main_m4;
input         rlast_cpu2main_m4;
input         rvalid_cpu2main_m4;
output        rready_cpu2main_m4;
output [2:0]  awuser_cpu2main_m4;
output [2:0]  aruser_cpu2main_m4;

// Instance: u_cd_cpu2peri, Port: cpu2peri_m3

output [11:0] awid_cpu2peri_m3;
output [31:0] awaddr_cpu2peri_m3;
output [7:0]  awlen_cpu2peri_m3;
output [2:0]  awsize_cpu2peri_m3;
output [1:0]  awburst_cpu2peri_m3;
output        awlock_cpu2peri_m3;
output [3:0]  awcache_cpu2peri_m3;
output [2:0]  awprot_cpu2peri_m3;
output        awvalid_cpu2peri_m3;
input         awready_cpu2peri_m3;
output [31:0] wdata_cpu2peri_m3;
output [3:0]  wstrb_cpu2peri_m3;
output        wlast_cpu2peri_m3;
output        wvalid_cpu2peri_m3;
input         wready_cpu2peri_m3;
input  [11:0] bid_cpu2peri_m3;
input  [1:0]  bresp_cpu2peri_m3;
input         bvalid_cpu2peri_m3;
output        bready_cpu2peri_m3;
output [11:0] arid_cpu2peri_m3;
output [31:0] araddr_cpu2peri_m3;
output [7:0]  arlen_cpu2peri_m3;
output [2:0]  arsize_cpu2peri_m3;
output [1:0]  arburst_cpu2peri_m3;
output        arlock_cpu2peri_m3;
output [3:0]  arcache_cpu2peri_m3;
output [2:0]  arprot_cpu2peri_m3;
output        arvalid_cpu2peri_m3;
input         arready_cpu2peri_m3;
input  [11:0] rid_cpu2peri_m3;
input  [31:0] rdata_cpu2peri_m3;
input  [1:0]  rresp_cpu2peri_m3;
input         rlast_cpu2peri_m3;
input         rvalid_cpu2peri_m3;
output        rready_cpu2peri_m3;

// Instance: u_cd_hsp2cpu, Port: hsp2cpu_s5

input  [7:0]  awid_hsp2cpu_s5;
input  [32:0] awaddr_hsp2cpu_s5;
input  [7:0]  awlen_hsp2cpu_s5;
input  [2:0]  awsize_hsp2cpu_s5;
input  [1:0]  awburst_hsp2cpu_s5;
input         awlock_hsp2cpu_s5;
input  [3:0]  awcache_hsp2cpu_s5;
input  [2:0]  awprot_hsp2cpu_s5;
input         awvalid_hsp2cpu_s5;
output        awready_hsp2cpu_s5;
input  [31:0] wdata_hsp2cpu_s5;
input  [3:0]  wstrb_hsp2cpu_s5;
input         wlast_hsp2cpu_s5;
input         wvalid_hsp2cpu_s5;
output        wready_hsp2cpu_s5;
output [7:0]  bid_hsp2cpu_s5;
output [1:0]  bresp_hsp2cpu_s5;
output        bvalid_hsp2cpu_s5;
input         bready_hsp2cpu_s5;
input  [7:0]  arid_hsp2cpu_s5;
input  [32:0] araddr_hsp2cpu_s5;
input  [7:0]  arlen_hsp2cpu_s5;
input  [2:0]  arsize_hsp2cpu_s5;
input  [1:0]  arburst_hsp2cpu_s5;
input         arlock_hsp2cpu_s5;
input  [3:0]  arcache_hsp2cpu_s5;
input  [2:0]  arprot_hsp2cpu_s5;
input         arvalid_hsp2cpu_s5;
output        arready_hsp2cpu_s5;
output [7:0]  rid_hsp2cpu_s5;
output [31:0] rdata_hsp2cpu_s5;
output [1:0]  rresp_hsp2cpu_s5;
output        rlast_hsp2cpu_s5;
output        rvalid_hsp2cpu_s5;
input         rready_hsp2cpu_s5;

// Instance: u_cd_iram, Port: iram_m1

output [32:0] haddr_iram_m1;
output [2:0]  hburst_iram_m1;
output [3:0]  hprot_iram_m1;
output [2:0]  hsize_iram_m1;
output [1:0]  htrans_iram_m1;
output [31:0] hwdata_iram_m1;
output        hwrite_iram_m1;
input  [31:0] hrdata_iram_m1;
input         hreadyout_iram_m1;
input         hresp_iram_m1;
output        hselx_iram_m1;
output        hready_iram_m1;

// Instance: u_cd_irom, Port: irom_m0

output [32:0] haddr_irom_m0;
output [2:0]  hburst_irom_m0;
output [3:0]  hprot_irom_m0;
output [2:0]  hsize_irom_m0;
output [1:0]  htrans_irom_m0;
output [31:0] hwdata_irom_m0;
output        hwrite_irom_m0;
input  [31:0] hrdata_irom_m0;
input         hreadyout_irom_m0;
input         hresp_irom_m0;
output        hselx_irom_m0;
output        hready_irom_m0;

//  Non-bus signals

input         cad7clk;
input         cad7resetn;
input         cpu2mainclk;
input         cpu2mainresetn;
input         cpu2periclk;
input         cpu2periresetn;
input         hsp2cpuclk;
input         hsp2cpuresetn;
input         iramclk;
input         iramresetn;
input         iromclk;
input         iromresetn;
input         mainclk;
input         mainclk_r;
input         mainresetn;
input         mainresetn_r;

endmodule
